import { useState, useEffect, createContext, useContext, ReactNode } from "react";

type Language = "he" | "en" | "es" | "zh" | "ar" | "ru";

const getStoredLanguage = (): Language => {
  const stored = localStorage.getItem("ui-language") as Language | null;
  const fallback = localStorage.getItem("app-language") as Language | null;
  return stored || fallback || "he";
};

const translations = {
  he: {
    personalArea: "אזור אישי", installApp: "התקנת אפליקציה", signOut: "התנתק", signedOutSuccess: "התנתקת בהצלחה", loading: "טוען...",
    dashboard: "דשבורד", personalTasks: "משימות אישיות", workTasks: "משימות עבודה", books: "ספרים", shows: "סדרות וסרטים", podcasts: "פודקאסטים", dailyRoutine: "לוז יומי", projects: "פרויקטים", courses: "קורסים", planner: "מתכנן לוז", deeply: "ZoneFlow", settings: "הגדרות", challenges: "אתגרים", restartGuide: "הפעל מדריך מחדש", restartGuideDesc: "הפעל את אשף ההדרכה מחדש כדי לסקור את כל התכונות.",
    security: "אבטחה", pinCode: "קוד גישה (PIN)", pinDescription: "דרוש קוד 4 ספרות בכל כניסה לאתר", changePin: "שנה קוד גישה", setPin: "הגדר קוד גישה", enterNewCode: "הזן קוד חדש:", cancel: "ביטול",
    customDashboards: "דשבורדים מותאמים אישית", customDashboardsDesc: "צור דשבורדים מותאמים לעקוב אחר כל דבר שתרצה (למידה, כושר, מתכונים ועוד). הם יופיעו כלשוניות בסרגל העליון.", newDashboard: "דשבורד חדש", chooseTemplate: "בחר תבנית", taskList: "רשימת משימות (כולל דשבורד)", trackingList: "רשימת מעקב (כמו ספרים/פודקאסטים)", kanban: "קנבן (לביצוע → בבדיקה → הושלם)", custom: "מותאם אישית", dashboardName: "שם הדשבורד", dashboardNamePlaceholder: 'לדוגמה: "לימודים", "כושר", "מתכונים"', statuses: "סטטוסים (מופרדים בפסיק)", statusesDesc: "הסטטוסים שיופיעו בתפריט הבחירה של כל פריט", showInMainDashboard: "הצג סיכום בדשבורד הראשי", createDashboard: "צור דשבורד", addNewDashboard: "הוסף דשבורד חדש",
    showTabs: "הצגת לשוניות", showTabsDesc: "בחר אילו לשוניות יוצגו בסרגל העליון. לשוניות מוסתרות לא יופיעו אבל הנתונים שלהן נשמרים.", displayedInDashboard: "מוצג בדשבורד", language: "שפה", languageDesc: "בחר את שפת הממשק", hebrew: "עברית", english: "English",
    newTask: "משימה חדשה", deleteTask: "מחק משימה", export: "ייצוא", noSort: "ללא מיון", byStatus: "לפי סטטוס", byPlannedEnd: "לפי סיום מתוכנן", byCreatedAt: "לפי תאריך יצירה", byOverdue: "לפי חריגה", byUrgent: "לפי דחיפות", done: "בוצע", notStarted: "טרם החל", inProgress: "בטיפול", completionRate: "אחוז ביצוע", activeTasks: "משימות פעילות", completed: "בוצעו", archive: "ארכיון", noTasksYet: "אין משימות עדיין", noArchivedTasks: "אין משימות בארכיון", noCompletedTasks: "אין משימות שבוצעו", addFirstTask: "הוסף משימה ראשונה", share: "שתף", similarTasks: "משימות דומות:", moveToSheet: "העבר משימה לגליון אחר", task: "משימה:", moveToSheetLabel: "העבר לגליון:", moveTask: "העבר משימה", aiHelp: "עזרה מ-AI", gettingSuggestions: "מקבל הצעות...", loadingTasks: "טוען משימות...",
    addEvent: "הוסף אירוע", deleteEvent: "מחק אירוע", eventTitle: "כותרת", eventDescription: "תיאור", startTime: "שעת התחלה", endTime: "שעת סיום", category: "קטגוריה", allDay: "כל היום", save: "שמור", delete: "מחק", today: "היום", day: "יום", week: "שבוע", month: "חודש", year: "שנה",
    addRecurringTask: "הוסף משימה חוזרת", frequency: "תדירות", daily: "יומי", weekly: "שבועי", monthly: "חודשי", yearly: "שנתי", thriceWeekly: "3 פעמים בשבוע", flexible: "גמיש", selectDays: "בחר ימים", sun: "א׳", mon: "ב׳", tue: "ג׳", wed: "ד׳", thu: "ה׳", fri: "ו׳", sat: "ש׳",
    addBook: "הוסף ספר", addShow: "הוסף סדרה", addPodcast: "הוסף פודקאסט", title: "כותרת", author: "מחבר", host: "מנחה", status: "סטטוס", notes: "הערות", toRead: "לקרוא", reading: "קורא", read: "נקרא", toWatch: "לצפות", watching: "צופה", watched: "נצפה", toListen: "להאזין", listening: "מאזין", listened: "נשמע",
    addProject: "הוסף פרויקט", projectName: "שם הפרויקט", description: "תיאור", targetDate: "תאריך יעד", active: "פעיל", onHold: "בהמתנה", completedStatus: "הושלם",
    addCourse: "הוסף קורס", courseName: "שם הקורס", syllabus: "סילבוס", lessons: "שיעורים",
    add: "הוסף", edit: "ערוך", remove: "הסר", confirm: "אשר", close: "סגור", search: "חיפוש", filter: "סינון", all: "הכל", none: "ללא",
    contactForm: "פנייה / תמיכה",
    recycleBin: "סל מחזור", emptyBin: "רוקן סל", recycleBinEmpty: "סל המחזור ריק", recycleBinNote: "פריטים נמחקים אוטומטית לאחר 7 ימים", restore: "שחזר", deletedAt: "נמחק", permanentDelete: "מחק לצמיתות",
    email: "מייל", emailAccounts: "חשבונות מייל", addConnection: "חבר חשבון", connectEmail: "חיבור חשבון מייל", chooseProvider: "בחר ספק מייל:", emailAddress: "כתובת מייל", noEmailConnections: "אין חשבונות מייל מחוברים", connectEmailDesc: "חבר Gmail או IMAP לניתוח אוטומטי", lastSync: "סנכרון אחרון", neverSynced: "לא סונכרן", sync: "סנכרן", confirmDisconnect: "לנתק את חשבון המייל?", emailSummary: "סיכום מיילים", recentEmails: "מיילים אחרונים", emailInsights: "תובנות מייל", emailsAnalyzed: "מיילים נותחו", oauthNote: "לאחר שמירה, תתבצע הפנייה לאימות חשבון.", password: "סיסמה", back: "חזור", connect: "חבר",
    editItem: "עריכת פריט",
    nutrition: "תזונה ושינה", dreams: "מפת חלומות", shopping: "קניות", payments: "הכנסות והוצאות", notesTab: "פתקים", sharingTab: "שיתופים",
    accessibilitySettings: "הגדרות נגישות", fontSize: "גודל גופן", highContrast: "ניגודיות גבוהה", disableAnimations: "השבת אנימציות", bigCursor: "סמן מוגדל", highlightLinks: "הדגש קישורים", reset: "איפוס", accessibilityStatement: "הצהרת נגישות", skipToContent: "דלג לתוכן הראשי", reduceFontSize: "הקטן גופן", increaseFontSize: "הגדל גופן",
    creditCard: "כרטיס אשראי", connectCreditCard: "חבר כרטיס אשראי", creditCardProvider: "חברת אשראי", username: "שם משתמש", syncNow: "סנכרן עכשיו", importCSV: "ייבוא קובץ CSV", importCreditCard: "ייבוא פירוט אשראי", transactions: "עסקאות", noTransactions: "אין עסקאות", lastFourDigits: "4 ספרות אחרונות", cardDisplayName: "שם הכרטיס", syncing: "מסנכרן...", syncSuccess: "סנכרון הושלם", syncError: "שגיאה בסנכרון", disconnectCard: "נתק כרטיס", confirmDisconnectCard: "לנתק את כרטיס האשראי?",
    bankConnections: "חיבורי בנק ואשראי", connectBank: "חבר בנק", bankConnectStarted: "נפתח חלון חיבור בנק", bankConnectError: "שגיאה בחיבור בנק", bankDisconnected: "חיבור בנק נמחק", noBankConnections: "אין חיבורי בנק. לחץ 'חבר בנק' כדי להתחיל.", syncComplete: "סנכרון הושלם", deleteError: "שגיאה במחיקה", loginRequired: "יש להתחבר מחדש", emailConnected: "חשבון מייל חובר", oauthError: "שגיאה בפתיחת OAuth", bankAndCredit: "בנק ואשראי",
    changePassword: "שנה סיסמה", currentPassword: "סיסמה נוכחית", newPassword: "סיסמה חדשה", confirmPassword: "אימות סיסמה", passwordChanged: "הסיסמה שונתה בהצלחה", passwordMismatch: "הסיסמאות לא תואמות", theme: "ערכת נושא", darkMode: "מצב כהה", lightMode: "מצב בהיר", systemMode: "לפי המערכת",
    a11yCommitment: "מחויבות לנגישות", a11yCommitmentText: "אנו מחויבים להנגיש את מערכת Tabro לכלל האוכלוסייה, כולל אנשים עם מוגבלויות, בהתאם לתקן הישראלי (ת\"י 5568) ולהנחיות WCAG 2.1 ברמה AA.", a11yWhatWeDid: "מה עשינו", a11yLimitations: "מגבלות ידועות", a11yLimitationsText: "ייתכנו רכיבים מסוימים שעדיין אינם מונגשים באופן מלא. אנו עובדים באופן שוטף על שיפור הנגישות.", a11yContact: "יצירת קשר", a11yContactText: "נתקלת בבעיית נגישות? נשמח לשמוע ממך. ניתן לפנות דרך טופס יצירת הקשר באתר.", lastUpdated: "עדכון אחרון",
    a11yFeatureKeyboard: "תמיכה מלאה בניווט מקלדת", a11yFeatureRtl: "תמיכה ב-RTL (ימין לשמאל) לעברית", a11yFeatureHeadings: "היררכיית כותרות תקינה (H1-H6)", a11yFeatureAria: "תוויות ARIA באלמנטים אינטראקטיביים", a11yFeatureContrast: "ניגודיות צבעים מספקת", a11yFeatureSkip: "כפתור \"דלג לתוכן\" (Skip Link) לניווט מהיר", a11yFeatureTheme: "מצב כהה ובהיר לנוחות צפייה", a11yFeatureForms: "טפסים עם תוויות ברורות והודעות שגיאה",
    // Payment Dashboard
    incomeAndExpenses: "הכנסות והוצאות", totalRemaining: "סה״כ נותר", excellentSurplus: "מצוין! יש לך עודף 👏", warningOverspend: "שים לב - ההוצאות עולות על ההכנסות ⚠️",
    income: "הכנסות", expenses: "הוצאות", overdue: "באיחור", budgetTarget: "יעד תקציב", budgetSaved: "יעד תקציב נשמר ✅",
    expensesLabel: "הוצאות", targetLabel: "יעד", budgetExceeded: "חריגה של", budgetRemaining: "נותרו",
    setBudgetTarget: "הגדר יעד תקציב", editing: "עריכה", saveBudget: "שמור", cancelBudget: "ביטול",
    weeklyPeriod: "שבועי", monthlyPeriod: "חודשי", quarterlyPeriod: "רבעוני", yearlyPeriod: "שנתי",
    rule503020: "כלל 50/30/20", needs: "צרכים", wants: "רצונות", savings: "חיסכון", targetPercent: "יעד",
    expenseBreakdown: "פילוח הוצאות", fixedExpenses: "הוצאות קבועות", variableExpenses: "הוצאות משתנות",
    incomeTab: "הכנסות והוצאות", historyTab: "היסטוריה", addTab: "הוסף", guidesTab: "מדריכים", aiAdvisor: "יועץ AI", bankCreditTab: "בנק ואשראי",
    noPaymentsYet: "אין תשלומים עדיין. הוסף הכנסה או הוצאה כדי להתחיל!", noHistoryYet: "אין עדיין נתונים. הוסף הכנסות והוצאות כדי לראות היסטוריה חודשית.",
    current: "נוכחי", detail: "פירוט", allItems: "כל הפריטים",
    incomeType: "הכנסה", expenseType: "הוצאה", incomeName: "שם ההכנסה (משכורת, פרילנס...)", expenseName: "שם ההוצאה (שכירות, חשמל...)",
    amount: "סכום", paymentMethod: "אמצעי תשלום (אשראי, מזומן...)", chooseCategory: "בחר קטגוריה", recurringExpense: "הוצאה/הכנסה קבועה (חוזרת כל חודש)",
    addIncome: "הוסף הכנסה", addExpense: "הוסף הוצאה", incomeAdded: "הכנסה נוספה ✅", expenseAdded: "הוצאה נוספה",
    aiFinancialAdvisor: "יועץ פיננסי AI", askAboutMoney: "שאל שאלה על הכסף שלך...", monthlySummaryBtn: "סיכום חודשי",
    monthlySummaryPrompt: "תן לי סיכום חודשי מפורט: מה הייתי צריך לשפר, מה עשיתי טוב, ומה הצעדים הבאים שלי.",
    exportLabel: "ייצוא", descriptionCol: "תיאור", amountCol: "סכום", typeCol: "סוג", categoryCol: "קטגוריה", paidCol: "שולם", dateCol: "תאריך", recurringCol: "קבוע", methodCol: "אמצעי תשלום", paymentsSheet: "תשלומים",
    balance: "מאזן", error: "שגיאה",
    // Categories (payment)
    catSalary: "משכורת", catFreelance: "פרילנס", catHousing: "דיור", catRent: "שכירות", catMortgage: "משכנתא", catGroceries: "סופר", catFood: "אוכל", catFuel: "דלק", catTransport: "תחבורה", catElectricity: "חשמל", catWater: "מים", catGas: "גז", catInternet: "אינטרנט", catPhone: "טלפון", catInsurance: "ביטוחים", catBills: "חשבונות", catShopping: "קניות", catEntertainment: "בילויים", catEducation: "חינוך", catHealth: "בריאות", catSavings: "חיסכון", catInvestments: "השקעות", catOther: "אחר",
    // Financial guides
    guideSaving: "מדריך לחיסכון כסף", guideInvest: "איך להשקיע נכון", guideImpulse: "הימנעות מקניות אימפולסיביות", guideTips: "טיפים פיננסיים",
    guide503020Rule: "כלל 50/30/20", guide503020Text: "חלק את ההכנסה: 50% לצרכים, 30% לרצונות, 20% לחיסכון. זה הבסיס לכל תקציב בריא.",
    guidePayYourselfFirst: "שלם לעצמך קודם", guidePayYourselfFirstText: "ברגע שהמשכורת נכנסת, העבר אוטומטית 10-20% לחשבון חיסכון נפרד.",
    guide24HourRule: "כלל 24 השעות", guide24HourRuleText: "לפני כל קנייה מעל ₪100, חכה 24 שעות. ב-70% מהמקרים תגלה שאתה לא באמת צריך את זה.",
    guide52WeekChallenge: "אתגר 52 שבועות", guide52WeekChallengeText: "שבוע 1 = חסוך ₪10, שבוע 2 = ₪20... בסוף השנה יהיו לך אלפי שקלים.",
    guideEmergencyFund: "קרן חירום קודם", guideEmergencyFundText: "לפני כל השקעה, בנה קרן חירום של 3-6 חודשי הוצאות.",
    guideCompoundInterest: "ריבית דריבית", guideCompoundInterestText: "₪500/חודש עם 8% תשואה = ₪450,000 אחרי 20 שנה. הזמן הוא הנכס הכי חשוב.",
    guideETF: "קרנות מחקות (ETF)", guideETFText: "90% מהמשקיעים לא מנצחים את המדד. השקע בקרנות שמחקות S&P 500.",
    guideIdentifyTriggers: "זהה את הטריגרים", guideIdentifyTriggersText: "שעמום, עצב, FOMO. כשאתה מרגיש דחף לקנות - שאל 'מה אני מרגיש עכשיו?'",
    guideWorkHours: "חשב בשעות עבודה", guideWorkHoursText: "מוצר ב-₪300 ואתה מרוויח ₪60/שעה = 5 שעות עבודה. שווה?",
    guideDeleteApps: "מחק אפליקציות קניות", guideDeleteAppsText: "הקושי הנוסף של לפתוח דפדפן = פחות קניות דחף.",
    guideAutomation: "אוטומציה פיננסית", guideAutomationText: "הגדר העברות אוטומטיות ביום המשכורת: חיסכון, השקעות, ביטוחים.",
    guideAvalanche: "שיטת המפולת לחובות", guideAvalancheText: "שלם קודם את החוב עם הריבית הגבוהה ביותר.",
    guideDisclaimer: "⚠️ הערה", guideDisclaimerText: "כל המידע כאן הוא לצרכי למידה בלבד ואינו מהווה ייעוץ השקעות מקצועי.",
    // Months
    january: "ינואר", february: "פברואר", march: "מרץ", april: "אפריל", may: "מאי", june: "יוני", july: "יולי", august: "אוגוסט", september: "ספטמבר", october: "אוקטובר", november: "נובמבר", december: "דצמבר",
    // Settings panel
    personalDetails: "פרטים אישיים", personalDetailsDesc: "השם שלך יוצג בגליונות משותפים כדי שאחרים ידעו מי הוסיף או עדכן משימות.", firstName: "שם פרטי", lastName: "שם משפחה",
    designAndColors: "עיצוב וצבעים", designDesc: "אפשר לבחור ערכת צבעים לכל האתר ולעבור בין מראה בהיר וכהה.", colorScheme: "ערכת צבעים", displayMode: "מצב תצוגה", light: "בהיר", dark: "כהה",
    font: "גופן", fontDesc: "בחר את הגופן שמתאים לך. השינוי חל על כל האתר.",
    interfaceLayout: "מבנה ממשק", layoutDesc: "בחר את סגנון הניווט שהכי נוח לך. השינוי מיידי.",
    layoutTabs: "לשוניות", layoutTabsDesc: "סרגל עליון קלאסי", layoutSidebar: "סרגל צד", layoutSidebarDesc: "תפריט צד מתקפל", layoutCompact: "קומפקטי", layoutCompactDesc: "תפריטים נפתחים", layoutBottomNav: "סרגל תחתון", layoutBottomNavDesc: "ניווט מסך קטן", layoutHamburger: "המבורגר", layoutHamburgerDesc: "תפריט נפתח", layoutCards: "כרטיסיות", layoutCardsDesc: "דשבורד ראשי", layoutSplitView: "פאנל כפול", layoutSplitViewDesc: "ניווט + תוכן",
    customColorsTitle: "התאמת צבעים אישית", customColorsDesc: "שנה צבעים ספציפיים לעיצוב הנוכחי. השינויים נשמרים אוטומטית.", primaryColor: "צבע ראשי", backgroundColor: "צבע רקע", cardColor: "צבע כרטיס", resetToDefault: "איפוס לברירת מחדל",
    pinActivated: "קוד גישה הופעל", pinDeactivated: "קוד גישה בוטל", pinUpdated: "קוד הגישה עודכן בהצלחה!", settingsError: "שגיאה בעדכון ההגדרות",
    changePasswordTitle: "שינוי סיסמה", passwordMinLength: "סיסמה חייבת להכיל לפחות 6 תווים", changing: "משנה...",
    deleteAccount: "מחיקת חשבון", deleteAccountDesc: "מחיקת החשבון תסיר את כל הנתונים שלך לצמיתות. פעולה זו אינה ניתנת לביטול.", deleteMyAccount: "מחק את החשבון שלי", deleteConfirmFirst: "⚠️ פעולה זו תמחק את כל הנתונים שלך לצמיתות. לא ניתן לבטל פעולה זו.\n\nהאם להמשיך?", deleteConfirmFinal: "אישור אחרון - האם אתה בטוח שברצונך למחוק את החשבון? תישלח הודעת אימייל לאישור סופי.", deleteEmailSent: "נשלח אימייל אישור מחיקה לכתובת המייל שלך. לחץ על הקישור באימייל כדי לאשר.", deleteEmailSentShort: "לאחר לחיצה, תישלח הודעת אימייל עם קישור אישור. רק לאחר לחיצה על הקישור החשבון יימחק.", deleteRequestError: "שגיאה בשליחת בקשת מחיקה",
    customListsDashboards: "רשימות ודשבורדים מותאמים אישית", customListsDesc: "צור קטגוריות רשימות ודשבורדים מותאמים לעקוב אחר כל דבר שתרצה (למידה, כושר, מתכונים ועוד). הן יופיעו כלשוניות בסרגל העליון.", displayedInDashboardBadge: "מוצג בדשבורד", nameChanged: "שם שונה",
    templateTasks: "רשימת משימות (כולל דשבורד)", templateTodo: "רשימת To-Do", templateShopping: "רשימת קניות", templateTracking: "קטגוריית רשימות", templateLearning: "רשימת למידה/קריאה", templateKanban: "קנבן", templateCustom: "מותאם אישית",
    createCategory: "צור קטגוריה", addListDashboard: "הוסף קטגוריית רשימות/דשבורד חדש", enterName: "יש להזין שם", enterStatus: "יש להזין לפחות סטטוס אחד", dashboardAdded: "הדשבורד נוסף בהצלחה!", dashboardCreateError: "שגיאה ביצירת דשבורד", deletedSuccessfully: "נמחק בהצלחה", deleteError2: "שגיאה במחיקה", deleteConfirmBoard: "למחוק את \"{name}\"? כל הפריטים בו יימחקו.",
    tabVisibility: "הצגת לשוניות", tabVisibilityDesc: "בחר אילו לשוניות יוצגו בסרגל העליון. לשוניות מוסתרות לא יופיעו אבל הנתונים שלהן נשמרים.",
    notifications: "התראות",
    hebrewDate: "תאריך עברי", hebrewDateDesc: "הצג תאריך עברי בדשבורד הראשי (לפי הלוח העברי).", showHebrewDate: "הצג תאריך עברי",
    languageTitle: "שפה / Language", languageChoose: "בחר את שפת הממשק / Choose interface language",
  },
  en: {
    personalArea: "Personal Area", installApp: "Install App", signOut: "Sign Out", signedOutSuccess: "Signed out successfully", loading: "Loading...",
    dashboard: "Dashboard", personalTasks: "Personal Tasks", workTasks: "Work Tasks", books: "Books", shows: "Shows & Movies", podcasts: "Podcasts", dailyRoutine: "Daily Routine", projects: "Projects", courses: "Courses", planner: "Planner", deeply: "ZoneFlow", settings: "Settings", challenges: "Challenges", restartGuide: "Restart Guide", restartGuideDesc: "Re-launch the onboarding wizard to review all features.",
    security: "Security", pinCode: "Access Code (PIN)", pinDescription: "Require a 4-digit code on every login", changePin: "Change PIN", setPin: "Set PIN", enterNewCode: "Enter new code:", cancel: "Cancel",
    customDashboards: "Custom Dashboards", customDashboardsDesc: "Create custom dashboards to track anything you want.", newDashboard: "New Dashboard", chooseTemplate: "Choose Template", taskList: "Task List (with dashboard)", trackingList: "Tracking List", kanban: "Kanban", custom: "Custom", dashboardName: "Dashboard Name", dashboardNamePlaceholder: 'e.g. "Learning", "Fitness"', statuses: "Statuses (comma-separated)", statusesDesc: "Statuses in the selection menu", showInMainDashboard: "Show in main dashboard", createDashboard: "Create Dashboard", addNewDashboard: "Add New Dashboard",
    showTabs: "Tab Visibility", showTabsDesc: "Choose which tabs are displayed.", displayedInDashboard: "Displayed in dashboard", language: "Language", languageDesc: "Choose the interface language", hebrew: "עברית", english: "English",
    newTask: "New Task", deleteTask: "Delete Task", export: "Export", noSort: "No Sort", byStatus: "By Status", byPlannedEnd: "By Planned End", byCreatedAt: "By Created Date", byOverdue: "By Overdue", byUrgent: "By Urgency", done: "Done", notStarted: "Not Started", inProgress: "In Progress", completionRate: "Completion Rate", activeTasks: "Active Tasks", completed: "Completed", archive: "Archive", noTasksYet: "No tasks yet", noArchivedTasks: "No archived tasks", noCompletedTasks: "No completed tasks", addFirstTask: "Add first task", share: "Share", similarTasks: "Similar tasks:", moveToSheet: "Move task to another sheet", task: "Task:", moveToSheetLabel: "Move to sheet:", moveTask: "Move Task", aiHelp: "AI Help", gettingSuggestions: "Getting suggestions...", loadingTasks: "Loading tasks...",
    addEvent: "Add Event", deleteEvent: "Delete Event", eventTitle: "Title", eventDescription: "Description", startTime: "Start Time", endTime: "End Time", category: "Category", allDay: "All Day", save: "Save", delete: "Delete", today: "Today", day: "Day", week: "Week", month: "Month", year: "Year",
    addRecurringTask: "Add Recurring Task", frequency: "Frequency", daily: "Daily", weekly: "Weekly", monthly: "Monthly", yearly: "Yearly", thriceWeekly: "3 Times a Week", flexible: "Flexible", selectDays: "Select Days", sun: "Sun", mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat: "Sat",
    addBook: "Add Book", addShow: "Add Show", addPodcast: "Add Podcast", title: "Title", author: "Author", host: "Host", status: "Status", notes: "Notes", toRead: "To Read", reading: "Reading", read: "Read", toWatch: "To Watch", watching: "Watching", watched: "Watched", toListen: "To Listen", listening: "Listening", listened: "Listened",
    addProject: "Add Project", projectName: "Project Name", description: "Description", targetDate: "Target Date", active: "Active", onHold: "On Hold", completedStatus: "Completed",
    addCourse: "Add Course", courseName: "Course Name", syllabus: "Syllabus", lessons: "Lessons",
    add: "Add", edit: "Edit", remove: "Remove", confirm: "Confirm", close: "Close", search: "Search", filter: "Filter", all: "All", none: "None",
    contactForm: "Contact / Support",
    recycleBin: "Recycle Bin", emptyBin: "Empty Bin", recycleBinEmpty: "Recycle bin is empty", recycleBinNote: "Items are automatically deleted after 7 days", restore: "Restore", deletedAt: "Deleted", permanentDelete: "Delete permanently",
    email: "Email", emailAccounts: "Email Accounts", addConnection: "Connect Account", connectEmail: "Connect Email Account", chooseProvider: "Choose email provider:", emailAddress: "Email Address", noEmailConnections: "No email accounts connected", connectEmailDesc: "Connect Gmail or IMAP for automatic analysis", lastSync: "Last sync", neverSynced: "Never synced", sync: "Sync", confirmDisconnect: "Disconnect email account?", emailSummary: "Email Summary", recentEmails: "Recent Emails", emailInsights: "Email Insights", emailsAnalyzed: "emails analyzed", oauthNote: "After saving, you'll be redirected for authentication.", password: "Password", back: "Back", connect: "Connect",
    editItem: "Edit Item",
    nutrition: "Nutrition & Sleep", dreams: "Dream Map", shopping: "Shopping", payments: "Income & Expenses", notesTab: "Notes", sharingTab: "Sharing",
    accessibilitySettings: "Accessibility Settings", fontSize: "Font Size", highContrast: "High Contrast", disableAnimations: "Disable Animations", bigCursor: "Large Cursor", highlightLinks: "Highlight Links", reset: "Reset", accessibilityStatement: "Accessibility Statement", skipToContent: "Skip to main content", reduceFontSize: "Reduce font size", increaseFontSize: "Increase font size",
    creditCard: "Credit Card", connectCreditCard: "Connect Credit Card", creditCardProvider: "Card Provider", username: "Username", syncNow: "Sync Now", importCSV: "Import CSV", importCreditCard: "Import Credit Card Statement", transactions: "Transactions", noTransactions: "No transactions", lastFourDigits: "Last 4 digits", cardDisplayName: "Card Name", syncing: "Syncing...", syncSuccess: "Sync complete", syncError: "Sync error", disconnectCard: "Disconnect Card", confirmDisconnectCard: "Disconnect this credit card?",
    bankConnections: "Bank & Credit Connections", connectBank: "Connect Bank", bankConnectStarted: "Bank connection window opened", bankConnectError: "Error connecting bank", bankDisconnected: "Bank connection removed", noBankConnections: "No bank connections. Click 'Connect Bank' to start.", syncComplete: "Sync complete", deleteError: "Error deleting", loginRequired: "Please sign in again", emailConnected: "Email account connected", oauthError: "Error opening OAuth", bankAndCredit: "Bank & Credit",
    changePassword: "Change Password", currentPassword: "Current Password", newPassword: "New Password", confirmPassword: "Confirm Password", passwordChanged: "Password changed successfully", passwordMismatch: "Passwords don't match", theme: "Theme", darkMode: "Dark Mode", lightMode: "Light Mode", systemMode: "System",
    a11yCommitment: "Commitment to Accessibility", a11yCommitmentText: "We are committed to making Tabro accessible to all users, including people with disabilities, in compliance with WCAG 2.1 Level AA guidelines.", a11yWhatWeDid: "What We Did", a11yLimitations: "Known Limitations", a11yLimitationsText: "Some components may not yet be fully accessible. We are continuously working to improve accessibility.", a11yContact: "Contact Us", a11yContactText: "Encountered an accessibility issue? We'd love to hear from you. Please reach out through the contact form on the site.", lastUpdated: "Last updated",
    a11yFeatureKeyboard: "Full keyboard navigation support", a11yFeatureRtl: "RTL (right-to-left) support for Hebrew", a11yFeatureHeadings: "Proper heading hierarchy (H1-H6)", a11yFeatureAria: "ARIA labels on interactive elements", a11yFeatureContrast: "Sufficient color contrast", a11yFeatureSkip: "Skip to content link for quick navigation", a11yFeatureTheme: "Dark and light modes for viewing comfort", a11yFeatureForms: "Forms with clear labels and error messages",
    // Payment Dashboard
    incomeAndExpenses: "Income & Expenses", totalRemaining: "Total Remaining", excellentSurplus: "Excellent! You have a surplus 👏", warningOverspend: "Warning - expenses exceed income ⚠️",
    income: "Income", expenses: "Expenses", overdue: "Overdue", budgetTarget: "Budget Target", budgetSaved: "Budget target saved ✅",
    expensesLabel: "Expenses", targetLabel: "Target", budgetExceeded: "Exceeded by", budgetRemaining: "Remaining",
    setBudgetTarget: "Set budget target", editing: "Edit", saveBudget: "Save", cancelBudget: "Cancel",
    weeklyPeriod: "Weekly", monthlyPeriod: "Monthly", quarterlyPeriod: "Quarterly", yearlyPeriod: "Yearly",
    rule503020: "50/30/20 Rule", needs: "Needs", wants: "Wants", savings: "Savings", targetPercent: "Target",
    expenseBreakdown: "Expense Breakdown", fixedExpenses: "Fixed Expenses", variableExpenses: "Variable Expenses",
    incomeTab: "Income & Expenses", historyTab: "History", addTab: "Add", guidesTab: "Guides", aiAdvisor: "AI Advisor", bankCreditTab: "Bank & Credit",
    noPaymentsYet: "No payments yet. Add income or expenses to get started!", noHistoryYet: "No data yet. Add income and expenses to see monthly history.",
    current: "Current", detail: "Details", allItems: "All Items",
    incomeType: "Income", expenseType: "Expense", incomeName: "Income name (salary, freelance...)", expenseName: "Expense name (rent, electricity...)",
    amount: "Amount", paymentMethod: "Payment method (credit, cash...)", chooseCategory: "Choose category", recurringExpense: "Recurring income/expense (monthly)",
    addIncome: "Add Income", addExpense: "Add Expense", incomeAdded: "Income added ✅", expenseAdded: "Expense added",
    aiFinancialAdvisor: "AI Financial Advisor", askAboutMoney: "Ask a question about your finances...", monthlySummaryBtn: "Monthly Summary",
    monthlySummaryPrompt: "Give me a detailed monthly summary: what should I improve, what I did well, and my next steps.",
    exportLabel: "Export", descriptionCol: "Description", amountCol: "Amount", typeCol: "Type", categoryCol: "Category", paidCol: "Paid", dateCol: "Date", recurringCol: "Recurring", methodCol: "Payment Method", paymentsSheet: "Payments",
    balance: "Balance", error: "Error",
    catSalary: "Salary", catFreelance: "Freelance", catHousing: "Housing", catRent: "Rent", catMortgage: "Mortgage", catGroceries: "Groceries", catFood: "Food", catFuel: "Fuel", catTransport: "Transport", catElectricity: "Electricity", catWater: "Water", catGas: "Gas", catInternet: "Internet", catPhone: "Phone", catInsurance: "Insurance", catBills: "Bills", catShopping: "Shopping", catEntertainment: "Entertainment", catEducation: "Education", catHealth: "Health", catSavings: "Savings", catInvestments: "Investments", catOther: "Other",
    guideSaving: "Money Saving Guide", guideInvest: "How to Invest Wisely", guideImpulse: "Avoiding Impulse Purchases", guideTips: "Financial Tips",
    guide503020Rule: "50/30/20 Rule", guide503020Text: "Split income: 50% needs, 30% wants, 20% savings. The foundation of any healthy budget.",
    guidePayYourselfFirst: "Pay Yourself First", guidePayYourselfFirstText: "When your paycheck arrives, automatically transfer 10-20% to a savings account.",
    guide24HourRule: "24-Hour Rule", guide24HourRuleText: "Before any purchase over $50, wait 24 hours. 70% of the time you'll realize you don't need it.",
    guide52WeekChallenge: "52-Week Challenge", guide52WeekChallengeText: "Week 1 = save $5, week 2 = $10... By year's end you'll have thousands.",
    guideEmergencyFund: "Emergency Fund First", guideEmergencyFundText: "Before investing, build an emergency fund of 3-6 months of expenses.",
    guideCompoundInterest: "Compound Interest", guideCompoundInterestText: "$500/month at 8% return = $450,000 after 20 years. Time is your greatest asset.",
    guideETF: "Index Funds (ETF)", guideETFText: "90% of investors can't beat the index. Invest in funds that track the S&P 500.",
    guideIdentifyTriggers: "Identify Triggers", guideIdentifyTriggersText: "Boredom, sadness, FOMO. When you feel an urge to buy — ask 'what am I feeling right now?'",
    guideWorkHours: "Think in Work Hours", guideWorkHoursText: "A $100 product and you earn $20/hour = 5 work hours. Worth it?",
    guideDeleteApps: "Delete Shopping Apps", guideDeleteAppsText: "The extra effort of opening a browser = fewer impulse purchases.",
    guideAutomation: "Financial Automation", guideAutomationText: "Set up automatic transfers on payday: savings, investments, insurance.",
    guideAvalanche: "Debt Avalanche Method", guideAvalancheText: "Pay off the debt with the highest interest rate first.",
    guideDisclaimer: "⚠️ Note", guideDisclaimerText: "All information here is for educational purposes only and does not constitute professional investment advice.",
    january: "January", february: "February", march: "March", april: "April", may: "May", june: "June", july: "July", august: "August", september: "September", october: "October", november: "November", december: "December",
    personalDetails: "Personal Details", personalDetailsDesc: "Your name will be displayed in shared sheets so others know who added or updated tasks.", firstName: "First Name", lastName: "Last Name",
    designAndColors: "Design & Colors", designDesc: "Choose a color scheme for the entire site and switch between light and dark modes.", colorScheme: "Color Scheme", displayMode: "Display Mode", light: "Light", dark: "Dark",
    font: "Font", fontDesc: "Choose the font that suits you. The change applies to the entire site.",
    interfaceLayout: "Interface Layout", layoutDesc: "Choose the navigation style that's most comfortable for you. Changes are immediate.",
    layoutTabs: "Tabs", layoutTabsDesc: "Classic top bar", layoutSidebar: "Sidebar", layoutSidebarDesc: "Collapsible side menu", layoutCompact: "Compact", layoutCompactDesc: "Dropdown menus", layoutBottomNav: "Bottom Nav", layoutBottomNavDesc: "Small screen nav", layoutHamburger: "Hamburger", layoutHamburgerDesc: "Dropdown menu", layoutCards: "Cards", layoutCardsDesc: "Main dashboard", layoutSplitView: "Split View", layoutSplitViewDesc: "Nav + content",
    customColorsTitle: "Custom Color Adjustment", customColorsDesc: "Change specific colors for the current design. Changes save automatically.", primaryColor: "Primary Color", backgroundColor: "Background Color", cardColor: "Card Color", resetToDefault: "Reset to Default",
    pinActivated: "Access code activated", pinDeactivated: "Access code deactivated", pinUpdated: "Access code updated successfully!", settingsError: "Error updating settings",
    changePasswordTitle: "Change Password", passwordMinLength: "Password must be at least 6 characters", changing: "Changing...",
    deleteAccount: "Delete Account", deleteAccountDesc: "Deleting your account will permanently remove all your data. This action cannot be undone.", deleteMyAccount: "Delete My Account", deleteConfirmFirst: "⚠️ This will permanently delete all your data. This cannot be undone.\n\nContinue?", deleteConfirmFinal: "Final confirmation — are you sure you want to delete your account? A confirmation email will be sent.", deleteEmailSent: "A confirmation email has been sent. Click the link in the email to confirm.", deleteEmailSentShort: "After clicking, a confirmation email will be sent. The account will only be deleted after clicking the link.", deleteRequestError: "Error sending delete request",
    customListsDashboards: "Custom Lists & Dashboards", customListsDesc: "Create custom category lists and dashboards to track anything you want (learning, fitness, recipes, etc.). They'll appear as tabs in the top bar.", displayedInDashboardBadge: "Displayed in dashboard", nameChanged: "Name changed",
    templateTasks: "Task List (with dashboard)", templateTodo: "To-Do List", templateShopping: "Shopping List", templateTracking: "Category List", templateLearning: "Learning/Reading List", templateKanban: "Kanban", templateCustom: "Custom",
    createCategory: "Create Category", addListDashboard: "Add New List/Dashboard Category", enterName: "Please enter a name", enterStatus: "Please enter at least one status", dashboardAdded: "Dashboard added successfully!", dashboardCreateError: "Error creating dashboard", deletedSuccessfully: "Deleted successfully", deleteError2: "Error deleting", deleteConfirmBoard: "Delete \"{name}\"? All items in it will be deleted.",
    tabVisibility: "Tab Visibility", tabVisibilityDesc: "Choose which tabs are displayed in the top bar. Hidden tabs won't appear but their data is preserved.",
    notifications: "Notifications",
    hebrewDate: "Hebrew Date", hebrewDateDesc: "Show Hebrew date on the main dashboard (according to the Hebrew calendar).", showHebrewDate: "Show Hebrew Date",
    languageTitle: "Language", languageChoose: "Choose interface language",
  },
  es: {
    personalArea: "Área Personal", installApp: "Instalar App", signOut: "Cerrar Sesión", signedOutSuccess: "Sesión cerrada", loading: "Cargando...",
    dashboard: "Panel", personalTasks: "Tareas Personales", workTasks: "Tareas de Trabajo", books: "Libros", shows: "Series y Películas", podcasts: "Podcasts", dailyRoutine: "Rutina Diaria", projects: "Proyectos", courses: "Cursos", planner: "Planificador", deeply: "ZoneFlow", settings: "Ajustes", challenges: "Desafíos", restartGuide: "Reiniciar Guía", restartGuideDesc: "Reiniciar el asistente de configuración.",
    security: "Seguridad", pinCode: "Código de Acceso (PIN)", pinDescription: "Requiere un código de 4 dígitos en cada inicio de sesión", changePin: "Cambiar PIN", setPin: "Establecer PIN", enterNewCode: "Ingresa nuevo código:", cancel: "Cancelar",
    customDashboards: "Paneles Personalizados", customDashboardsDesc: "Crea paneles personalizados para hacer seguimiento de lo que quieras.", newDashboard: "Nuevo Panel", chooseTemplate: "Elegir Plantilla", taskList: "Lista de Tareas", trackingList: "Lista de Seguimiento", kanban: "Kanban", custom: "Personalizado", dashboardName: "Nombre del Panel", dashboardNamePlaceholder: 'Ej: "Estudios", "Fitness"', statuses: "Estados (separados por coma)", statusesDesc: "Estados en el menú de selección", showInMainDashboard: "Mostrar en panel principal", createDashboard: "Crear Panel", addNewDashboard: "Agregar Nuevo Panel",
    showTabs: "Visibilidad de Pestañas", showTabsDesc: "Elige qué pestañas se muestran.", displayedInDashboard: "Mostrado en panel", language: "Idioma", languageDesc: "Elige el idioma de la interfaz", hebrew: "עברית", english: "English",
    newTask: "Nueva Tarea", deleteTask: "Eliminar Tarea", export: "Exportar", noSort: "Sin Orden", byStatus: "Por Estado", byPlannedEnd: "Por Fecha Límite", byCreatedAt: "Por Fecha de Creación", byOverdue: "Por Vencimiento", byUrgent: "Por Urgencia", done: "Hecho", notStarted: "No Iniciado", inProgress: "En Progreso", completionRate: "Tasa de Completitud", activeTasks: "Tareas Activas", completed: "Completadas", archive: "Archivo", noTasksYet: "Sin tareas aún", noArchivedTasks: "Sin tareas archivadas", noCompletedTasks: "Sin tareas completadas", addFirstTask: "Agregar primera tarea", share: "Compartir", similarTasks: "Tareas similares:", moveToSheet: "Mover a otra hoja", task: "Tarea:", moveToSheetLabel: "Mover a hoja:", moveTask: "Mover Tarea", aiHelp: "Ayuda IA", gettingSuggestions: "Obteniendo sugerencias...", loadingTasks: "Cargando tareas...",
    addEvent: "Agregar Evento", deleteEvent: "Eliminar Evento", eventTitle: "Título", eventDescription: "Descripción", startTime: "Hora de Inicio", endTime: "Hora de Fin", category: "Categoría", allDay: "Todo el Día", save: "Guardar", delete: "Eliminar", today: "Hoy", day: "Día", week: "Semana", month: "Mes", year: "Año",
    addRecurringTask: "Agregar Tarea Recurrente", frequency: "Frecuencia", daily: "Diario", weekly: "Semanal", monthly: "Mensual", yearly: "Anual", thriceWeekly: "3 veces por semana", flexible: "Flexible", selectDays: "Seleccionar Días", sun: "Dom", mon: "Lun", tue: "Mar", wed: "Mié", thu: "Jue", fri: "Vie", sat: "Sáb",
    addBook: "Agregar Libro", addShow: "Agregar Serie", addPodcast: "Agregar Podcast", title: "Título", author: "Autor", host: "Presentador", status: "Estado", notes: "Notas", toRead: "Por Leer", reading: "Leyendo", read: "Leído", toWatch: "Por Ver", watching: "Viendo", watched: "Visto", toListen: "Por Escuchar", listening: "Escuchando", listened: "Escuchado",
    addProject: "Agregar Proyecto", projectName: "Nombre del Proyecto", description: "Descripción", targetDate: "Fecha Objetivo", active: "Activo", onHold: "En Espera", completedStatus: "Completado",
    addCourse: "Agregar Curso", courseName: "Nombre del Curso", syllabus: "Programa", lessons: "Lecciones",
    add: "Agregar", edit: "Editar", remove: "Eliminar", confirm: "Confirmar", close: "Cerrar", search: "Buscar", filter: "Filtrar", all: "Todos", none: "Ninguno",
    contactForm: "Contacto / Soporte",
    recycleBin: "Papelera", emptyBin: "Vaciar Papelera", recycleBinEmpty: "La papelera está vacía", recycleBinNote: "Los elementos se eliminan automáticamente después de 7 días", restore: "Restaurar", deletedAt: "Eliminado", permanentDelete: "Eliminar permanentemente",
    email: "Correo", emailAccounts: "Cuentas de Correo", addConnection: "Conectar Cuenta", connectEmail: "Conectar Cuenta de Correo", chooseProvider: "Elige proveedor de correo:", emailAddress: "Dirección de Correo", noEmailConnections: "Sin cuentas de correo conectadas", connectEmailDesc: "Conecta Gmail o IMAP para análisis automático", lastSync: "Última sincronización", neverSynced: "Nunca sincronizado", sync: "Sincronizar", confirmDisconnect: "¿Desconectar cuenta de correo?", emailSummary: "Resumen de Correo", recentEmails: "Correos Recientes", emailInsights: "Análisis de Correo", emailsAnalyzed: "correos analizados", oauthNote: "Después de guardar, serás redirigido para autenticación.", password: "Contraseña", back: "Atrás", connect: "Conectar",
    editItem: "Editar Elemento",
    nutrition: "Nutrición y Sueño", dreams: "Mapa de Sueños", shopping: "Compras", payments: "Ingresos y Gastos", notesTab: "Notas", sharingTab: "Compartir",
    accessibilitySettings: "Configuración de Accesibilidad", fontSize: "Tamaño de Fuente", highContrast: "Alto Contraste", disableAnimations: "Desactivar Animaciones", bigCursor: "Cursor Grande", highlightLinks: "Resaltar Enlaces", reset: "Restablecer", accessibilityStatement: "Declaración de Accesibilidad", skipToContent: "Ir al contenido principal", reduceFontSize: "Reducir fuente", increaseFontSize: "Aumentar fuente",
    creditCard: "Tarjeta de Crédito", connectCreditCard: "Conectar Tarjeta", creditCardProvider: "Proveedor de Tarjeta", username: "Usuario", syncNow: "Sincronizar Ahora", importCSV: "Importar CSV", importCreditCard: "Importar Estado de Cuenta", transactions: "Transacciones", noTransactions: "Sin transacciones", lastFourDigits: "Últimos 4 dígitos", cardDisplayName: "Nombre de Tarjeta", syncing: "Sincronizando...", syncSuccess: "Sincronización completa", syncError: "Error de sincronización", disconnectCard: "Desconectar Tarjeta", confirmDisconnectCard: "¿Desconectar esta tarjeta?",
    bankConnections: "Conexiones Bancarias", connectBank: "Conectar Banco", bankConnectStarted: "Ventana de conexión bancaria abierta", bankConnectError: "Error al conectar banco", bankDisconnected: "Conexión bancaria eliminada", noBankConnections: "Sin conexiones bancarias. Haz clic en 'Conectar Banco'.", syncComplete: "Sincronización completa", deleteError: "Error al eliminar", loginRequired: "Inicia sesión nuevamente", emailConnected: "Cuenta de correo conectada", oauthError: "Error al abrir OAuth", bankAndCredit: "Banco y Crédito",
    changePassword: "Cambiar Contraseña", currentPassword: "Contraseña Actual", newPassword: "Nueva Contraseña", confirmPassword: "Confirmar Contraseña", passwordChanged: "Contraseña cambiada", passwordMismatch: "Las contraseñas no coinciden", theme: "Tema", darkMode: "Modo Oscuro", lightMode: "Modo Claro", systemMode: "Sistema",
    a11yCommitment: "Compromiso con la Accesibilidad", a11yCommitmentText: "Estamos comprometidos a hacer Tabro accesible para todos los usuarios, incluidas personas con discapacidades, cumpliendo con WCAG 2.1 Nivel AA.", a11yWhatWeDid: "Qué Hicimos", a11yLimitations: "Limitaciones Conocidas", a11yLimitationsText: "Algunos componentes pueden no ser totalmente accesibles. Trabajamos continuamente en mejorar.", a11yContact: "Contáctanos", a11yContactText: "¿Encontraste un problema de accesibilidad? Contáctanos a través del formulario del sitio.", lastUpdated: "Última actualización",
    a11yFeatureKeyboard: "Soporte completo de navegación por teclado", a11yFeatureRtl: "Soporte RTL para hebreo", a11yFeatureHeadings: "Jerarquía de encabezados correcta", a11yFeatureAria: "Etiquetas ARIA en elementos interactivos", a11yFeatureContrast: "Contraste de color suficiente", a11yFeatureSkip: "Enlace para saltar al contenido", a11yFeatureTheme: "Modos claro y oscuro", a11yFeatureForms: "Formularios con etiquetas claras",
    incomeAndExpenses: "Ingresos y Gastos", totalRemaining: "Total Restante", excellentSurplus: "¡Excelente! Tienes superávit 👏", warningOverspend: "Atención - los gastos superan los ingresos ⚠️",
    income: "Ingresos", expenses: "Gastos", overdue: "Vencido", budgetTarget: "Meta de Presupuesto", budgetSaved: "Meta guardada ✅",
    expensesLabel: "Gastos", targetLabel: "Meta", budgetExceeded: "Excedido en", budgetRemaining: "Restante",
    setBudgetTarget: "Establecer meta", editing: "Editar", saveBudget: "Guardar", cancelBudget: "Cancelar",
    weeklyPeriod: "Semanal", monthlyPeriod: "Mensual", quarterlyPeriod: "Trimestral", yearlyPeriod: "Anual",
    rule503020: "Regla 50/30/20", needs: "Necesidades", wants: "Deseos", savings: "Ahorro", targetPercent: "Meta",
    expenseBreakdown: "Desglose de Gastos", fixedExpenses: "Gastos Fijos", variableExpenses: "Gastos Variables",
    incomeTab: "Ingresos y Gastos", historyTab: "Historial", addTab: "Agregar", guidesTab: "Guías", aiAdvisor: "Asesor IA", bankCreditTab: "Banco y Crédito",
    noPaymentsYet: "Sin pagos aún. ¡Agrega ingresos o gastos para empezar!", noHistoryYet: "Sin datos aún. Agrega ingresos y gastos para ver el historial.",
    current: "Actual", detail: "Detalles", allItems: "Todos los Elementos",
    incomeType: "Ingreso", expenseType: "Gasto", incomeName: "Nombre del ingreso (salario, freelance...)", expenseName: "Nombre del gasto (alquiler, electricidad...)",
    amount: "Monto", paymentMethod: "Método de pago (crédito, efectivo...)", chooseCategory: "Elegir categoría", recurringExpense: "Ingreso/gasto recurrente (mensual)",
    addIncome: "Agregar Ingreso", addExpense: "Agregar Gasto", incomeAdded: "Ingreso agregado ✅", expenseAdded: "Gasto agregado",
    aiFinancialAdvisor: "Asesor Financiero IA", askAboutMoney: "Pregunta sobre tus finanzas...", monthlySummaryBtn: "Resumen Mensual",
    monthlySummaryPrompt: "Dame un resumen mensual detallado: qué mejorar, qué hice bien, y mis próximos pasos.",
    exportLabel: "Exportar", descriptionCol: "Descripción", amountCol: "Monto", typeCol: "Tipo", categoryCol: "Categoría", paidCol: "Pagado", dateCol: "Fecha", recurringCol: "Recurrente", methodCol: "Método de Pago", paymentsSheet: "Pagos",
    balance: "Balance", error: "Error",
    catSalary: "Salario", catFreelance: "Freelance", catHousing: "Vivienda", catRent: "Alquiler", catMortgage: "Hipoteca", catGroceries: "Supermercado", catFood: "Comida", catFuel: "Combustible", catTransport: "Transporte", catElectricity: "Electricidad", catWater: "Agua", catGas: "Gas", catInternet: "Internet", catPhone: "Teléfono", catInsurance: "Seguros", catBills: "Facturas", catShopping: "Compras", catEntertainment: "Entretenimiento", catEducation: "Educación", catHealth: "Salud", catSavings: "Ahorro", catInvestments: "Inversiones", catOther: "Otro",
    guideSaving: "Guía de Ahorro", guideInvest: "Cómo Invertir", guideImpulse: "Evitar Compras Impulsivas", guideTips: "Consejos Financieros",
    guide503020Rule: "Regla 50/30/20", guide503020Text: "Divide ingresos: 50% necesidades, 30% deseos, 20% ahorro.",
    guidePayYourselfFirst: "Págate Primero", guidePayYourselfFirstText: "Cuando llegue tu sueldo, transfiere automáticamente 10-20% a ahorros.",
    guide24HourRule: "Regla de 24 Horas", guide24HourRuleText: "Antes de compras mayores a $50, espera 24 horas.",
    guide52WeekChallenge: "Reto de 52 Semanas", guide52WeekChallengeText: "Semana 1 = ahorra $5, semana 2 = $10... Al final del año tendrás miles.",
    guideEmergencyFund: "Fondo de Emergencia", guideEmergencyFundText: "Antes de invertir, crea un fondo de emergencia de 3-6 meses.",
    guideCompoundInterest: "Interés Compuesto", guideCompoundInterestText: "$500/mes al 8% = $450,000 en 20 años.",
    guideETF: "Fondos Indexados (ETF)", guideETFText: "90% de inversores no superan el índice. Invierte en fondos indexados.",
    guideIdentifyTriggers: "Identifica Detonantes", guideIdentifyTriggersText: "Aburrimiento, tristeza, FOMO. Pregúntate '¿qué siento ahora?'",
    guideWorkHours: "Piensa en Horas de Trabajo", guideWorkHoursText: "Un producto de $100 y ganas $20/hora = 5 horas. ¿Vale la pena?",
    guideDeleteApps: "Elimina Apps de Compras", guideDeleteAppsText: "La dificultad extra de abrir el navegador = menos compras impulsivas.",
    guideAutomation: "Automatización Financiera", guideAutomationText: "Configura transferencias automáticas el día de pago.",
    guideAvalanche: "Método Avalancha", guideAvalancheText: "Paga primero la deuda con mayor interés.",
    guideDisclaimer: "⚠️ Nota", guideDisclaimerText: "Toda la información es solo educativa y no constituye asesoría financiera profesional.",
    january: "Enero", february: "Febrero", march: "Marzo", april: "Abril", may: "Mayo", june: "Junio", july: "Julio", august: "Agosto", september: "Septiembre", october: "Octubre", november: "Noviembre", december: "Diciembre",
    personalDetails: "Datos Personales", personalDetailsDesc: "Tu nombre se mostrará en hojas compartidas.", firstName: "Nombre", lastName: "Apellido",
    designAndColors: "Diseño y Colores", designDesc: "Elige esquema de colores y modo claro/oscuro.", colorScheme: "Esquema de Colores", displayMode: "Modo de Visualización", light: "Claro", dark: "Oscuro",
    font: "Fuente", fontDesc: "Elige la fuente. El cambio se aplica a todo el sitio.",
    interfaceLayout: "Diseño de Interfaz", layoutDesc: "Elige el estilo de navegación más cómodo.",
    layoutTabs: "Pestañas", layoutTabsDesc: "Barra superior", layoutSidebar: "Barra lateral", layoutSidebarDesc: "Menú lateral", layoutCompact: "Compacto", layoutCompactDesc: "Menús desplegables", layoutBottomNav: "Nav inferior", layoutBottomNavDesc: "Nav móvil", layoutHamburger: "Hamburguesa", layoutHamburgerDesc: "Menú desplegable", layoutCards: "Tarjetas", layoutCardsDesc: "Panel principal", layoutSplitView: "Vista dividida", layoutSplitViewDesc: "Nav + contenido",
    customColorsTitle: "Colores Personalizados", customColorsDesc: "Cambia colores específicos del diseño actual.", primaryColor: "Color Principal", backgroundColor: "Color de Fondo", cardColor: "Color de Tarjeta", resetToDefault: "Restablecer",
    pinActivated: "Código activado", pinDeactivated: "Código desactivado", pinUpdated: "¡Código actualizado!", settingsError: "Error al actualizar",
    changePasswordTitle: "Cambiar Contraseña", passwordMinLength: "La contraseña debe tener al menos 6 caracteres", changing: "Cambiando...",
    deleteAccount: "Eliminar Cuenta", deleteAccountDesc: "Eliminar tu cuenta borrará todos tus datos permanentemente.", deleteMyAccount: "Eliminar mi cuenta", deleteConfirmFirst: "⚠️ Esto eliminará todos tus datos permanentemente.\n\n¿Continuar?", deleteConfirmFinal: "Confirmación final — ¿seguro que quieres eliminar tu cuenta?", deleteEmailSent: "Se envió un email de confirmación.", deleteEmailSentShort: "Se enviará un email de confirmación.", deleteRequestError: "Error al enviar solicitud",
    customListsDashboards: "Listas y Paneles Personalizados", customListsDesc: "Crea listas y paneles personalizados.", displayedInDashboardBadge: "En panel", nameChanged: "Nombre cambiado",
    templateTasks: "Lista de tareas", templateTodo: "Lista To-Do", templateShopping: "Lista de compras", templateTracking: "Lista de categorías", templateLearning: "Lista de lectura", templateKanban: "Kanban", templateCustom: "Personalizado",
    createCategory: "Crear categoría", addListDashboard: "Agregar lista/panel nuevo", enterName: "Ingresa un nombre", enterStatus: "Ingresa al menos un estado", dashboardAdded: "¡Panel agregado!", dashboardCreateError: "Error al crear", deletedSuccessfully: "Eliminado", deleteError2: "Error al eliminar", deleteConfirmBoard: "¿Eliminar \"{name}\"? Todos los elementos se borrarán.",
    tabVisibility: "Visibilidad de Pestañas", tabVisibilityDesc: "Elige qué pestañas se muestran.",
    notifications: "Notificaciones",
    hebrewDate: "Fecha Hebrea", hebrewDateDesc: "Mostrar fecha hebrea en el panel principal.", showHebrewDate: "Mostrar fecha hebrea",
    languageTitle: "Idioma", languageChoose: "Elige el idioma de la interfaz",
  },
  zh: {
    personalArea: "个人区域", installApp: "安装应用", signOut: "退出", signedOutSuccess: "已成功退出", loading: "加载中...",
    dashboard: "仪表盘", personalTasks: "个人任务", workTasks: "工作任务", books: "书籍", shows: "剧集和电影", podcasts: "播客", dailyRoutine: "每日日程", projects: "项目", courses: "课程", planner: "计划器", deeply: "ZoneFlow", settings: "设置", challenges: "挑战", restartGuide: "重启向导", restartGuideDesc: "重新启动引导向导。",
    security: "安全", pinCode: "访问码 (PIN)", pinDescription: "每次登录需要4位数密码", changePin: "更改PIN", setPin: "设置PIN", enterNewCode: "输入新密码:", cancel: "取消",
    customDashboards: "自定义面板", customDashboardsDesc: "创建自定义面板来跟踪任何事物。", newDashboard: "新面板", chooseTemplate: "选择模板", taskList: "任务列表", trackingList: "跟踪列表", kanban: "看板", custom: "自定义", dashboardName: "面板名称", dashboardNamePlaceholder: '例如："学习"、"健身"', statuses: "状态（逗号分隔）", statusesDesc: "选择菜单中的状态", showInMainDashboard: "在主面板显示", createDashboard: "创建面板", addNewDashboard: "添加新面板",
    showTabs: "显示标签", showTabsDesc: "选择显示哪些标签。", displayedInDashboard: "在面板中显示", language: "语言", languageDesc: "选择界面语言", hebrew: "עברית", english: "English",
    newTask: "新任务", deleteTask: "删除任务", export: "导出", noSort: "无排序", byStatus: "按状态", byPlannedEnd: "按截止日期", byCreatedAt: "按创建日期", byOverdue: "按逾期", byUrgent: "按紧急程度", done: "完成", notStarted: "未开始", inProgress: "进行中", completionRate: "完成率", activeTasks: "活跃任务", completed: "已完成", archive: "归档", noTasksYet: "暂无任务", noArchivedTasks: "无归档任务", noCompletedTasks: "无已完成任务", addFirstTask: "添加第一个任务", share: "分享", similarTasks: "类似任务:", moveToSheet: "移动到其他表", task: "任务:", moveToSheetLabel: "移动到表:", moveTask: "移动任务", aiHelp: "AI帮助", gettingSuggestions: "获取建议中...", loadingTasks: "加载任务中...",
    addEvent: "添加事件", deleteEvent: "删除事件", eventTitle: "标题", eventDescription: "描述", startTime: "开始时间", endTime: "结束时间", category: "分类", allDay: "全天", save: "保存", delete: "删除", today: "今天", day: "日", week: "周", month: "月", year: "年",
    addRecurringTask: "添加重复任务", frequency: "频率", daily: "每天", weekly: "每周", monthly: "每月", yearly: "每年", thriceWeekly: "每周3次", flexible: "灵活", selectDays: "选择日期", sun: "日", mon: "一", tue: "二", wed: "三", thu: "四", fri: "五", sat: "六",
    addBook: "添加书籍", addShow: "添加剧集", addPodcast: "添加播客", title: "标题", author: "作者", host: "主持人", status: "状态", notes: "备注", toRead: "待读", reading: "在读", read: "已读", toWatch: "待看", watching: "在看", watched: "已看", toListen: "待听", listening: "在听", listened: "已听",
    addProject: "添加项目", projectName: "项目名称", description: "描述", targetDate: "目标日期", active: "活跃", onHold: "暂停", completedStatus: "已完成",
    addCourse: "添加课程", courseName: "课程名称", syllabus: "大纲", lessons: "课时",
    add: "添加", edit: "编辑", remove: "移除", confirm: "确认", close: "关闭", search: "搜索", filter: "筛选", all: "全部", none: "无",
    contactForm: "联系 / 支持",
    recycleBin: "回收站", emptyBin: "清空回收站", recycleBinEmpty: "回收站为空", recycleBinNote: "项目将在7天后自动删除", restore: "恢复", deletedAt: "已删除", permanentDelete: "永久删除",
    email: "邮件", emailAccounts: "邮件账户", addConnection: "连接账户", connectEmail: "连接邮件账户", chooseProvider: "选择邮件提供商：", emailAddress: "邮件地址", noEmailConnections: "没有连接的邮件账户", connectEmailDesc: "连接Gmail或IMAP进行自动分析", lastSync: "上次同步", neverSynced: "从未同步", sync: "同步", confirmDisconnect: "断开邮件账户？", emailSummary: "邮件摘要", recentEmails: "最近邮件", emailInsights: "邮件洞察", emailsAnalyzed: "封邮件已分析", oauthNote: "保存后将跳转至身份验证页面。", password: "密码", back: "返回", connect: "连接",
    editItem: "编辑项目",
    nutrition: "营养与睡眠", dreams: "梦想地图", shopping: "购物", payments: "收入与支出", notesTab: "便签", sharingTab: "分享",
    accessibilitySettings: "无障碍设置", fontSize: "字体大小", highContrast: "高对比度", disableAnimations: "禁用动画", bigCursor: "大光标", highlightLinks: "突出显示链接", reset: "重置", accessibilityStatement: "无障碍声明", skipToContent: "跳至主要内容", reduceFontSize: "缩小字体", increaseFontSize: "放大字体",
    creditCard: "信用卡", connectCreditCard: "连接信用卡", creditCardProvider: "发卡机构", username: "用户名", syncNow: "立即同步", importCSV: "导入CSV", importCreditCard: "导入信用卡账单", transactions: "交易记录", noTransactions: "没有交易", lastFourDigits: "后4位", cardDisplayName: "卡片名称", syncing: "同步中...", syncSuccess: "同步完成", syncError: "同步错误", disconnectCard: "断开卡片", confirmDisconnectCard: "断开此信用卡？",
    bankConnections: "银行连接", connectBank: "连接银行", bankConnectStarted: "银行连接窗口已打开", bankConnectError: "连接银行时出错", bankDisconnected: "银行连接已删除", noBankConnections: "暂无银行连接。点击'连接银行'开始。", syncComplete: "同步完成", deleteError: "删除出错", loginRequired: "请重新登录", emailConnected: "邮件账户已连接", oauthError: "打开OAuth出错", bankAndCredit: "银行与信用卡",
    changePassword: "更改密码", currentPassword: "当前密码", newPassword: "新密码", confirmPassword: "确认密码", passwordChanged: "密码已更改", passwordMismatch: "密码不匹配", theme: "主题", darkMode: "深色模式", lightMode: "浅色模式", systemMode: "系统",
    a11yCommitment: "无障碍承诺", a11yCommitmentText: "我们致力于让Tabro对所有用户（包括残障人士）无障碍使用，符合WCAG 2.1 AA级标准。", a11yWhatWeDid: "我们做了什么", a11yLimitations: "已知限制", a11yLimitationsText: "某些组件可能尚未完全无障碍。我们持续改进中。", a11yContact: "联系我们", a11yContactText: "遇到无障碍问题？请通过网站联系表单与我们联系。", lastUpdated: "最后更新",
    a11yFeatureKeyboard: "完整键盘导航支持", a11yFeatureRtl: "RTL支持", a11yFeatureHeadings: "正确的标题层次结构", a11yFeatureAria: "交互元素的ARIA标签", a11yFeatureContrast: "足够的颜色对比度", a11yFeatureSkip: "跳至内容链接", a11yFeatureTheme: "深色和浅色模式", a11yFeatureForms: "表单带清晰标签和错误消息",
    incomeAndExpenses: "收入与支出", totalRemaining: "总剩余", excellentSurplus: "太棒了！有盈余 👏", warningOverspend: "注意 - 支出超过收入 ⚠️",
    income: "收入", expenses: "支出", overdue: "逾期", budgetTarget: "预算目标", budgetSaved: "预算目标已保存 ✅",
    expensesLabel: "支出", targetLabel: "目标", budgetExceeded: "超支", budgetRemaining: "剩余",
    setBudgetTarget: "设置预算目标", editing: "编辑", saveBudget: "保存", cancelBudget: "取消",
    weeklyPeriod: "每周", monthlyPeriod: "每月", quarterlyPeriod: "每季", yearlyPeriod: "每年",
    rule503020: "50/30/20法则", needs: "需求", wants: "欲望", savings: "储蓄", targetPercent: "目标",
    expenseBreakdown: "支出分类", fixedExpenses: "固定支出", variableExpenses: "可变支出",
    incomeTab: "收支", historyTab: "历史", addTab: "添加", guidesTab: "指南", aiAdvisor: "AI顾问", bankCreditTab: "银行与信用卡",
    noPaymentsYet: "暂无记录。添加收入或支出开始使用！", noHistoryYet: "暂无数据。添加收支以查看月度历史。",
    current: "当前", detail: "详情", allItems: "所有项目",
    incomeType: "收入", expenseType: "支出", incomeName: "收入名称（工资、自由职业...）", expenseName: "支出名称（房租、电费...）",
    amount: "金额", paymentMethod: "支付方式（信用卡、现金...）", chooseCategory: "选择分类", recurringExpense: "固定收支（每月重复）",
    addIncome: "添加收入", addExpense: "添加支出", incomeAdded: "收入已添加 ✅", expenseAdded: "支出已添加",
    aiFinancialAdvisor: "AI财务顾问", askAboutMoney: "关于财务的问题...", monthlySummaryBtn: "月度总结",
    monthlySummaryPrompt: "给我一份详细的月度总结：需要改进什么，做得好的地方，以及下一步。",
    exportLabel: "导出", descriptionCol: "描述", amountCol: "金额", typeCol: "类型", categoryCol: "分类", paidCol: "已付", dateCol: "日期", recurringCol: "固定", methodCol: "支付方式", paymentsSheet: "支付",
    balance: "余额", error: "错误",
    catSalary: "工资", catFreelance: "自由职业", catHousing: "住房", catRent: "房租", catMortgage: "按揭", catGroceries: "超市", catFood: "餐饮", catFuel: "燃油", catTransport: "交通", catElectricity: "电费", catWater: "水费", catGas: "燃气", catInternet: "网络", catPhone: "电话", catInsurance: "保险", catBills: "账单", catShopping: "购物", catEntertainment: "娱乐", catEducation: "教育", catHealth: "健康", catSavings: "储蓄", catInvestments: "投资", catOther: "其他",
    guideSaving: "省钱指南", guideInvest: "如何正确投资", guideImpulse: "避免冲动消费", guideTips: "理财建议",
    guide503020Rule: "50/30/20法则", guide503020Text: "收入分配：50%需求，30%欲望，20%储蓄。",
    guidePayYourselfFirst: "先付给自己", guidePayYourselfFirstText: "工资到账后，自动转10-20%到储蓄账户。",
    guide24HourRule: "24小时法则", guide24HourRuleText: "超过50美元的购买前等24小时。",
    guide52WeekChallenge: "52周挑战", guide52WeekChallengeText: "第1周存5元，第2周存10元...年底将有数千元。",
    guideEmergencyFund: "先建应急基金", guideEmergencyFundText: "投资前先建立3-6个月的应急基金。",
    guideCompoundInterest: "复利", guideCompoundInterestText: "每月500元，8%收益=20年后45万元。",
    guideETF: "指数基金(ETF)", guideETFText: "90%的投资者跑不赢指数。投资追踪标普500的基金。",
    guideIdentifyTriggers: "识别触发因素", guideIdentifyTriggersText: "无聊、悲伤、FOMO。问自己'我现在感觉怎样？'",
    guideWorkHours: "用工作时间换算", guideWorkHoursText: "100元产品，时薪20元=5小时工作。值得吗？",
    guideDeleteApps: "删除购物应用", guideDeleteAppsText: "打开浏览器的额外步骤=减少冲动消费。",
    guideAutomation: "财务自动化", guideAutomationText: "在发薪日设置自动转账：储蓄、投资、保险。",
    guideAvalanche: "雪崩还债法", guideAvalancheText: "先还利率最高的债务。",
    guideDisclaimer: "⚠️ 注意", guideDisclaimerText: "所有信息仅供学习，不构成专业投资建议。",
    january: "一月", february: "二月", march: "三月", april: "四月", may: "五月", june: "六月", july: "七月", august: "八月", september: "九月", october: "十月", november: "十一月", december: "十二月",
    personalDetails: "个人资料", personalDetailsDesc: "您的姓名将显示在共享表格中。", firstName: "名", lastName: "姓",
    designAndColors: "设计和颜色", designDesc: "选择配色方案和明暗模式。", colorScheme: "配色方案", displayMode: "显示模式", light: "浅色", dark: "深色",
    font: "字体", fontDesc: "选择适合您的字体。",
    interfaceLayout: "界面布局", layoutDesc: "选择最舒适的导航样式。",
    layoutTabs: "标签页", layoutTabsDesc: "顶部栏", layoutSidebar: "侧边栏", layoutSidebarDesc: "可折叠侧栏", layoutCompact: "紧凑", layoutCompactDesc: "下拉菜单", layoutBottomNav: "底部导航", layoutBottomNavDesc: "移动导航", layoutHamburger: "汉堡菜单", layoutHamburgerDesc: "弹出菜单", layoutCards: "卡片", layoutCardsDesc: "主面板", layoutSplitView: "分屏", layoutSplitViewDesc: "导航+内容",
    customColorsTitle: "自定义颜色", customColorsDesc: "更改当前设计的特定颜色。", primaryColor: "主色", backgroundColor: "背景色", cardColor: "卡片色", resetToDefault: "重置默认",
    pinActivated: "访问码已启用", pinDeactivated: "访问码已禁用", pinUpdated: "访问码更新成功！", settingsError: "更新设置出错",
    changePasswordTitle: "更改密码", passwordMinLength: "密码至少需要6个字符", changing: "更改中...",
    deleteAccount: "删除账户", deleteAccountDesc: "删除账户将永久移除所有数据。", deleteMyAccount: "删除我的账户", deleteConfirmFirst: "⚠️ 这将永久删除所有数据。\n\n继续？", deleteConfirmFinal: "最终确认 - 确定要删除账户？", deleteEmailSent: "已发送确认邮件。", deleteEmailSentShort: "点击后将发送确认邮件。", deleteRequestError: "发送请求出错",
    customListsDashboards: "自定义列表和面板", customListsDesc: "创建自定义列表和面板。", displayedInDashboardBadge: "在面板中", nameChanged: "名称已更改",
    templateTasks: "任务列表", templateTodo: "待办列表", templateShopping: "购物清单", templateTracking: "分类列表", templateLearning: "阅读列表", templateKanban: "看板", templateCustom: "自定义",
    createCategory: "创建分类", addListDashboard: "添加新列表/面板", enterName: "请输入名称", enterStatus: "请至少输入一个状态", dashboardAdded: "面板添加成功！", dashboardCreateError: "创建出错", deletedSuccessfully: "已删除", deleteError2: "删除出错", deleteConfirmBoard: "删除\"{name}\"？所有项目将被删除。",
    tabVisibility: "标签可见性", tabVisibilityDesc: "选择显示哪些标签。",
    notifications: "通知",
    hebrewDate: "希伯来日期", hebrewDateDesc: "在主面板显示希伯来日期。", showHebrewDate: "显示希伯来日期",
    languageTitle: "语言", languageChoose: "选择界面语言",
  },
  ar: {
    personalArea: "المنطقة الشخصية", installApp: "تثبيت التطبيق", signOut: "تسجيل الخروج", signedOutSuccess: "تم تسجيل الخروج بنجاح", loading: "جاري التحميل...",
    dashboard: "لوحة المعلومات", personalTasks: "مهام شخصية", workTasks: "مهام العمل", books: "كتب", shows: "مسلسلات وأفلام", podcasts: "بودكاست", dailyRoutine: "الروتين اليومي", projects: "مشاريع", courses: "دورات", planner: "المخطط", deeply: "Deeply", settings: "الإعدادات", challenges: "تحديات",
    security: "الأمان", pinCode: "رمز الوصول (PIN)", pinDescription: "يتطلب رمزاً من 4 أرقام عند كل تسجيل دخول", changePin: "تغيير PIN", setPin: "تعيين PIN", enterNewCode: "أدخل الرمز الجديد:", cancel: "إلغاء",
    customDashboards: "لوحات مخصصة", customDashboardsDesc: "أنشئ لوحات مخصصة لتتبع أي شيء تريده.", newDashboard: "لوحة جديدة", chooseTemplate: "اختر قالب", taskList: "قائمة المهام", trackingList: "قائمة التتبع", kanban: "كانبان", custom: "مخصص", dashboardName: "اسم اللوحة", dashboardNamePlaceholder: 'مثال: "دراسة", "لياقة"', statuses: "الحالات (مفصولة بفاصلة)", statusesDesc: "الحالات في قائمة الاختيار", showInMainDashboard: "عرض في اللوحة الرئيسية", createDashboard: "إنشاء لوحة", addNewDashboard: "إضافة لوحة جديدة",
    showTabs: "إظهار التبويبات", showTabsDesc: "اختر التبويبات المعروضة.", displayedInDashboard: "معروض في اللوحة", language: "اللغة", languageDesc: "اختر لغة الواجهة", hebrew: "עברית", english: "English",
    newTask: "مهمة جديدة", deleteTask: "حذف مهمة", export: "تصدير", noSort: "بدون ترتيب", byStatus: "حسب الحالة", byPlannedEnd: "حسب الموعد النهائي", byCreatedAt: "حسب تاريخ الإنشاء", byOverdue: "حسب التأخير", byUrgent: "حسب الأولوية", done: "تم", notStarted: "لم يبدأ", inProgress: "قيد التنفيذ", completionRate: "نسبة الإنجاز", activeTasks: "مهام نشطة", completed: "مكتملة", archive: "أرشيف", noTasksYet: "لا توجد مهام بعد", noArchivedTasks: "لا توجد مهام مؤرشفة", noCompletedTasks: "لا توجد مهام مكتملة", addFirstTask: "أضف أول مهمة", share: "مشاركة", similarTasks: "مهام مشابهة:", moveToSheet: "نقل إلى ورقة أخرى", task: "مهمة:", moveToSheetLabel: "نقل إلى:", moveTask: "نقل مهمة", aiHelp: "مساعدة AI", gettingSuggestions: "جاري الحصول على اقتراحات...", loadingTasks: "جاري تحميل المهام...",
    addEvent: "إضافة حدث", deleteEvent: "حذف حدث", eventTitle: "العنوان", eventDescription: "الوصف", startTime: "وقت البدء", endTime: "وقت الانتهاء", category: "الفئة", allDay: "طوال اليوم", save: "حفظ", delete: "حذف", today: "اليوم", day: "يوم", week: "أسبوع", month: "شهر", year: "سنة",
    addRecurringTask: "إضافة مهمة متكررة", frequency: "التكرار", daily: "يومي", weekly: "أسبوعي", monthly: "شهري", yearly: "سنوي", thriceWeekly: "3 مرات أسبوعياً", flexible: "مرن", selectDays: "اختر الأيام", sun: "أحد", mon: "اثن", tue: "ثلا", wed: "أرب", thu: "خمي", fri: "جمع", sat: "سبت",
    addBook: "إضافة كتاب", addShow: "إضافة مسلسل", addPodcast: "إضافة بودكاست", title: "العنوان", author: "المؤلف", host: "المقدم", status: "الحالة", notes: "ملاحظات", toRead: "للقراءة", reading: "أقرأ", read: "مقروء", toWatch: "للمشاهدة", watching: "أشاهد", watched: "شوهد", toListen: "للاستماع", listening: "أستمع", listened: "سُمع",
    addProject: "إضافة مشروع", projectName: "اسم المشروع", description: "الوصف", targetDate: "التاريخ المستهدف", active: "نشط", onHold: "معلق", completedStatus: "مكتمل",
    addCourse: "إضافة دورة", courseName: "اسم الدورة", syllabus: "المنهج", lessons: "الدروس",
    add: "إضافة", edit: "تعديل", remove: "إزالة", confirm: "تأكيد", close: "إغلاق", search: "بحث", filter: "تصفية", all: "الكل", none: "لا شيء",
    contactForm: "اتصل بنا / دعم",
    recycleBin: "سلة المحذوفات", emptyBin: "إفراغ السلة", recycleBinEmpty: "سلة المحذوفات فارغة", recycleBinNote: "تُحذف العناصر تلقائياً بعد 7 أيام", restore: "استعادة", deletedAt: "حُذف", permanentDelete: "حذف نهائي",
    email: "البريد", emailAccounts: "حسابات البريد", addConnection: "ربط حساب", connectEmail: "ربط حساب بريد", chooseProvider: "اختر مزود البريد:", emailAddress: "عنوان البريد", noEmailConnections: "لا توجد حسابات بريد مرتبطة", connectEmailDesc: "اربط Gmail أو IMAP للتحليل التلقائي", lastSync: "آخر مزامنة", neverSynced: "لم تتم المزامنة", sync: "مزامنة", confirmDisconnect: "فصل حساب البريد؟", emailSummary: "ملخص البريد", recentEmails: "رسائل حديثة", emailInsights: "تحليل البريد", emailsAnalyzed: "رسالة تم تحليلها", oauthNote: "بعد الحفظ، ستتم إعادة التوجيه للمصادقة.", password: "كلمة المرور", back: "رجوع", connect: "ربط",
    editItem: "تعديل العنصر",
    nutrition: "التغذية والنوم", dreams: "خريطة الأحلام", shopping: "التسوق", payments: "الدخل والمصروفات", notesTab: "ملاحظات", sharingTab: "مشاركة",
    accessibilitySettings: "إعدادات إمكانية الوصول", fontSize: "حجم الخط", highContrast: "تباين عالي", disableAnimations: "تعطيل الحركات", bigCursor: "مؤشر كبير", highlightLinks: "إبراز الروابط", reset: "إعادة تعيين", accessibilityStatement: "بيان إمكانية الوصول", skipToContent: "انتقل إلى المحتوى الرئيسي", reduceFontSize: "تصغير الخط", increaseFontSize: "تكبير الخط",
    creditCard: "بطاقة ائتمان", connectCreditCard: "ربط بطاقة ائتمان", creditCardProvider: "مزود البطاقة", username: "اسم المستخدم", syncNow: "مزامنة الآن", importCSV: "استيراد CSV", importCreditCard: "استيراد كشف حساب", transactions: "المعاملات", noTransactions: "لا توجد معاملات", lastFourDigits: "آخر 4 أرقام", cardDisplayName: "اسم البطاقة", syncing: "جاري المزامنة...", syncSuccess: "تمت المزامنة", syncError: "خطأ في المزامنة", disconnectCard: "فصل البطاقة", confirmDisconnectCard: "فصل هذه البطاقة؟",
    bankConnections: "اتصالات البنك", connectBank: "ربط بنك", bankConnectStarted: "تم فتح نافذة ربط البنك", bankConnectError: "خطأ في ربط البنك", bankDisconnected: "تم حذف اتصال البنك", noBankConnections: "لا توجد اتصالات بنكية. انقر 'ربط بنك' للبدء.", syncComplete: "اكتملت المزامنة", deleteError: "خطأ في الحذف", loginRequired: "يرجى تسجيل الدخول مجدداً", emailConnected: "تم ربط حساب البريد", oauthError: "خطأ في فتح OAuth", bankAndCredit: "البنك والائتمان",
    changePassword: "تغيير كلمة المرور", currentPassword: "كلمة المرور الحالية", newPassword: "كلمة مرور جديدة", confirmPassword: "تأكيد كلمة المرور", passwordChanged: "تم تغيير كلمة المرور", passwordMismatch: "كلمات المرور غير متطابقة", theme: "السمة", darkMode: "الوضع الداكن", lightMode: "الوضع الفاتح", systemMode: "النظام",
    a11yCommitment: "التزامنا بإمكانية الوصول", a11yCommitmentText: "نحن ملتزمون بجعل Tabro متاحاً لجميع المستخدمين بما في ذلك ذوي الإعاقة وفقاً لمعايير WCAG 2.1 AA.", a11yWhatWeDid: "ما فعلناه", a11yLimitations: "القيود المعروفة", a11yLimitationsText: "قد لا تكون بعض المكونات متاحة بالكامل بعد. نعمل باستمرار على التحسين.", a11yContact: "اتصل بنا", a11yContactText: "واجهت مشكلة في إمكانية الوصول؟ تواصل معنا عبر نموذج الاتصال.", lastUpdated: "آخر تحديث",
    a11yFeatureKeyboard: "دعم كامل للتنقل بلوحة المفاتيح", a11yFeatureRtl: "دعم RTL للعربية والعبرية", a11yFeatureHeadings: "تسلسل عناوين صحيح", a11yFeatureAria: "تسميات ARIA للعناصر التفاعلية", a11yFeatureContrast: "تباين ألوان كافٍ", a11yFeatureSkip: "رابط تخطي للمحتوى", a11yFeatureTheme: "وضع داكن وفاتح", a11yFeatureForms: "نماذج بتسميات واضحة",
    incomeAndExpenses: "الدخل والمصروفات", totalRemaining: "إجمالي المتبقي", excellentSurplus: "ممتاز! لديك فائض 👏", warningOverspend: "تنبيه - المصروفات تتجاوز الدخل ⚠️",
    income: "الدخل", expenses: "المصروفات", overdue: "متأخر", budgetTarget: "هدف الميزانية", budgetSaved: "تم حفظ هدف الميزانية ✅",
    expensesLabel: "المصروفات", targetLabel: "الهدف", budgetExceeded: "تجاوز بمقدار", budgetRemaining: "متبقي",
    setBudgetTarget: "تحديد هدف الميزانية", editing: "تعديل", saveBudget: "حفظ", cancelBudget: "إلغاء",
    weeklyPeriod: "أسبوعي", monthlyPeriod: "شهري", quarterlyPeriod: "ربع سنوي", yearlyPeriod: "سنوي",
    rule503020: "قاعدة 50/30/20", needs: "احتياجات", wants: "رغبات", savings: "ادخار", targetPercent: "الهدف",
    expenseBreakdown: "توزيع المصروفات", fixedExpenses: "مصروفات ثابتة", variableExpenses: "مصروفات متغيرة",
    incomeTab: "الدخل والمصروفات", historyTab: "السجل", addTab: "إضافة", guidesTab: "أدلة", aiAdvisor: "مستشار AI", bankCreditTab: "البنك والائتمان",
    noPaymentsYet: "لا توجد مدفوعات. أضف دخلاً أو مصروفاً للبدء!", noHistoryYet: "لا توجد بيانات بعد. أضف دخلاً ومصروفات لعرض السجل.",
    current: "الحالي", detail: "تفاصيل", allItems: "جميع العناصر",
    incomeType: "دخل", expenseType: "مصروف", incomeName: "اسم الدخل (راتب، عمل حر...)", expenseName: "اسم المصروف (إيجار، كهرباء...)",
    amount: "المبلغ", paymentMethod: "طريقة الدفع (بطاقة، نقداً...)", chooseCategory: "اختر الفئة", recurringExpense: "دخل/مصروف متكرر (شهري)",
    addIncome: "إضافة دخل", addExpense: "إضافة مصروف", incomeAdded: "تمت إضافة الدخل ✅", expenseAdded: "تمت إضافة المصروف",
    aiFinancialAdvisor: "مستشار مالي AI", askAboutMoney: "اسأل عن أموالك...", monthlySummaryBtn: "ملخص شهري",
    monthlySummaryPrompt: "أعطني ملخصاً شهرياً مفصلاً: ما يجب تحسينه، ما فعلته جيداً، والخطوات التالية.",
    exportLabel: "تصدير", descriptionCol: "الوصف", amountCol: "المبلغ", typeCol: "النوع", categoryCol: "الفئة", paidCol: "مدفوع", dateCol: "التاريخ", recurringCol: "متكرر", methodCol: "طريقة الدفع", paymentsSheet: "المدفوعات",
    balance: "الرصيد", error: "خطأ",
    catSalary: "راتب", catFreelance: "عمل حر", catHousing: "سكن", catRent: "إيجار", catMortgage: "رهن عقاري", catGroceries: "بقالة", catFood: "طعام", catFuel: "وقود", catTransport: "مواصلات", catElectricity: "كهرباء", catWater: "مياه", catGas: "غاز", catInternet: "إنترنت", catPhone: "هاتف", catInsurance: "تأمين", catBills: "فواتير", catShopping: "تسوق", catEntertainment: "ترفيه", catEducation: "تعليم", catHealth: "صحة", catSavings: "ادخار", catInvestments: "استثمارات", catOther: "أخرى",
    guideSaving: "دليل التوفير", guideInvest: "كيف تستثمر بذكاء", guideImpulse: "تجنب الشراء الاندفاعي", guideTips: "نصائح مالية",
    guide503020Rule: "قاعدة 50/30/20", guide503020Text: "قسّم الدخل: 50% احتياجات، 30% رغبات، 20% ادخار.",
    guidePayYourselfFirst: "ادفع لنفسك أولاً", guidePayYourselfFirstText: "عند وصول الراتب، حوّل تلقائياً 10-20% لحساب ادخار.",
    guide24HourRule: "قاعدة 24 ساعة", guide24HourRuleText: "قبل أي شراء يزيد عن 50$، انتظر 24 ساعة.",
    guide52WeekChallenge: "تحدي 52 أسبوعاً", guide52WeekChallengeText: "الأسبوع 1 = وفّر 5$، الأسبوع 2 = 10$... بنهاية العام سيكون لديك آلاف.",
    guideEmergencyFund: "صندوق الطوارئ أولاً", guideEmergencyFundText: "قبل الاستثمار، أنشئ صندوق طوارئ يكفي 3-6 أشهر.",
    guideCompoundInterest: "الفائدة المركبة", guideCompoundInterestText: "500$/شهر بعائد 8% = 450,000$ بعد 20 سنة.",
    guideETF: "صناديق المؤشرات (ETF)", guideETFText: "90% من المستثمرين لا يتغلبون على المؤشر.",
    guideIdentifyTriggers: "حدد المحفزات", guideIdentifyTriggersText: "ملل، حزن، FOMO. اسأل نفسك 'ماذا أشعر الآن؟'",
    guideWorkHours: "فكّر بساعات العمل", guideWorkHoursText: "منتج بـ100$ وتكسب 20$/ساعة = 5 ساعات عمل. يستحق؟",
    guideDeleteApps: "احذف تطبيقات التسوق", guideDeleteAppsText: "صعوبة فتح المتصفح = مشتريات اندفاعية أقل.",
    guideAutomation: "الأتمتة المالية", guideAutomationText: "أعدّ تحويلات تلقائية يوم الراتب.",
    guideAvalanche: "طريقة الانهيار الجليدي", guideAvalancheText: "سدد الدين ذو الفائدة الأعلى أولاً.",
    guideDisclaimer: "⚠️ ملاحظة", guideDisclaimerText: "جميع المعلومات هنا تعليمية فقط ولا تشكل نصيحة استثمارية مهنية.",
    january: "يناير", february: "فبراير", march: "مارس", april: "أبريل", may: "مايو", june: "يونيو", july: "يوليو", august: "أغسطس", september: "سبتمبر", october: "أكتوبر", november: "نوفمبر", december: "ديسمبر",
    personalDetails: "البيانات الشخصية", personalDetailsDesc: "سيظهر اسمك في الأوراق المشتركة.", firstName: "الاسم الأول", lastName: "اسم العائلة",
    designAndColors: "التصميم والألوان", designDesc: "اختر نظام ألوان ووضع فاتح/داكن.", colorScheme: "نظام الألوان", displayMode: "وضع العرض", light: "فاتح", dark: "داكن",
    font: "الخط", fontDesc: "اختر الخط المناسب لك.",
    interfaceLayout: "تخطيط الواجهة", layoutDesc: "اختر أسلوب التنقل الأنسب.",
    layoutTabs: "تبويبات", layoutTabsDesc: "شريط علوي", layoutSidebar: "شريط جانبي", layoutSidebarDesc: "قائمة جانبية", layoutCompact: "مضغوط", layoutCompactDesc: "قوائم منسدلة", layoutBottomNav: "تنقل سفلي", layoutBottomNavDesc: "تنقل الجوال", layoutHamburger: "هامبرغر", layoutHamburgerDesc: "قائمة منبثقة", layoutCards: "بطاقات", layoutCardsDesc: "لوحة رئيسية", layoutSplitView: "عرض مقسم", layoutSplitViewDesc: "تنقل + محتوى",
    customColorsTitle: "ألوان مخصصة", customColorsDesc: "غيّر ألوان التصميم الحالي.", primaryColor: "اللون الرئيسي", backgroundColor: "لون الخلفية", cardColor: "لون البطاقة", resetToDefault: "إعادة تعيين",
    pinActivated: "تم تفعيل رمز الوصول", pinDeactivated: "تم تعطيل رمز الوصول", pinUpdated: "تم تحديث رمز الوصول!", settingsError: "خطأ في التحديث",
    changePasswordTitle: "تغيير كلمة المرور", passwordMinLength: "كلمة المرور يجب أن تكون 6 أحرف على الأقل", changing: "جاري التغيير...",
    deleteAccount: "حذف الحساب", deleteAccountDesc: "حذف الحساب سيزيل جميع بياناتك نهائياً.", deleteMyAccount: "حذف حسابي", deleteConfirmFirst: "⚠️ سيتم حذف جميع بياناتك نهائياً.\n\nمتابعة؟", deleteConfirmFinal: "تأكيد نهائي - هل تريد حذف حسابك؟", deleteEmailSent: "تم إرسال بريد تأكيد.", deleteEmailSentShort: "سيتم إرسال بريد تأكيد.", deleteRequestError: "خطأ في إرسال الطلب",
    customListsDashboards: "قوائم ولوحات مخصصة", customListsDesc: "أنشئ قوائم ولوحات مخصصة.", displayedInDashboardBadge: "في اللوحة", nameChanged: "تم تغيير الاسم",
    templateTasks: "قائمة مهام", templateTodo: "قائمة مهام", templateShopping: "قائمة تسوق", templateTracking: "قائمة تصنيف", templateLearning: "قائمة قراءة", templateKanban: "كانبان", templateCustom: "مخصص",
    createCategory: "إنشاء تصنيف", addListDashboard: "إضافة قائمة/لوحة جديدة", enterName: "أدخل اسماً", enterStatus: "أدخل حالة واحدة على الأقل", dashboardAdded: "تمت إضافة اللوحة!", dashboardCreateError: "خطأ في الإنشاء", deletedSuccessfully: "تم الحذف", deleteError2: "خطأ في الحذف", deleteConfirmBoard: "حذف \"{name}\"؟ سيتم حذف جميع العناصر.",
    tabVisibility: "إظهار التبويبات", tabVisibilityDesc: "اختر التبويبات المعروضة.",
    notifications: "الإشعارات",
    hebrewDate: "التاريخ العبري", hebrewDateDesc: "عرض التاريخ العبري في اللوحة الرئيسية.", showHebrewDate: "عرض التاريخ العبري",
    languageTitle: "اللغة", languageChoose: "اختر لغة الواجهة",
  },
  ru: {
    personalArea: "Личный кабинет", installApp: "Установить приложение", signOut: "Выйти", signedOutSuccess: "Вы успешно вышли", loading: "Загрузка...",
    dashboard: "Панель управления", personalTasks: "Личные задачи", workTasks: "Рабочие задачи", books: "Книги", shows: "Сериалы и фильмы", podcasts: "Подкасты", dailyRoutine: "Ежедневный распорядок", projects: "Проекты", courses: "Курсы", planner: "Планировщик", deeply: "Deeply", settings: "Настройки", challenges: "Вызовы",
    security: "Безопасность", pinCode: "Код доступа (PIN)", pinDescription: "Требовать 4-значный код при каждом входе", changePin: "Изменить PIN", setPin: "Установить PIN", enterNewCode: "Введите новый код:", cancel: "Отмена",
    customDashboards: "Пользовательские панели", customDashboardsDesc: "Создавайте панели для отслеживания чего угодно.", newDashboard: "Новая панель", chooseTemplate: "Выбрать шаблон", taskList: "Список задач", trackingList: "Список отслеживания", kanban: "Канбан", custom: "Пользовательский", dashboardName: "Название панели", dashboardNamePlaceholder: 'Напр.: "Учёба", "Фитнес"', statuses: "Статусы (через запятую)", statusesDesc: "Статусы в меню выбора", showInMainDashboard: "Показать на главной панели", createDashboard: "Создать панель", addNewDashboard: "Добавить новую панель",
    showTabs: "Видимость вкладок", showTabsDesc: "Выберите, какие вкладки отображать.", displayedInDashboard: "Отображается на панели", language: "Язык", languageDesc: "Выберите язык интерфейса", hebrew: "עברית", english: "English",
    newTask: "Новая задача", deleteTask: "Удалить задачу", export: "Экспорт", noSort: "Без сортировки", byStatus: "По статусу", byPlannedEnd: "По сроку", byCreatedAt: "По дате создания", byOverdue: "По просрочке", byUrgent: "По срочности", done: "Выполнено", notStarted: "Не начато", inProgress: "В работе", completionRate: "Процент выполнения", activeTasks: "Активные задачи", completed: "Завершённые", archive: "Архив", noTasksYet: "Задач пока нет", noArchivedTasks: "Нет архивных задач", noCompletedTasks: "Нет завершённых задач", addFirstTask: "Добавить первую задачу", share: "Поделиться", similarTasks: "Похожие задачи:", moveToSheet: "Переместить на другой лист", task: "Задача:", moveToSheetLabel: "Переместить на лист:", moveTask: "Переместить задачу", aiHelp: "Помощь ИИ", gettingSuggestions: "Получение предложений...", loadingTasks: "Загрузка задач...",
    addEvent: "Добавить событие", deleteEvent: "Удалить событие", eventTitle: "Заголовок", eventDescription: "Описание", startTime: "Начало", endTime: "Окончание", category: "Категория", allDay: "Весь день", save: "Сохранить", delete: "Удалить", today: "Сегодня", day: "День", week: "Неделя", month: "Месяц", year: "Год",
    addRecurringTask: "Добавить повторяющуюся задачу", frequency: "Частота", daily: "Ежедневно", weekly: "Еженедельно", monthly: "Ежемесячно", yearly: "Ежегодно", thriceWeekly: "3 раза в неделю", flexible: "Гибкий", selectDays: "Выбрать дни", sun: "Вс", mon: "Пн", tue: "Вт", wed: "Ср", thu: "Чт", fri: "Пт", sat: "Сб",
    addBook: "Добавить книгу", addShow: "Добавить сериал", addPodcast: "Добавить подкаст", title: "Название", author: "Автор", host: "Ведущий", status: "Статус", notes: "Заметки", toRead: "К прочтению", reading: "Читаю", read: "Прочитано", toWatch: "К просмотру", watching: "Смотрю", watched: "Просмотрено", toListen: "К прослушиванию", listening: "Слушаю", listened: "Прослушано",
    addProject: "Добавить проект", projectName: "Название проекта", description: "Описание", targetDate: "Целевая дата", active: "Активный", onHold: "На паузе", completedStatus: "Завершён",
    addCourse: "Добавить курс", courseName: "Название курса", syllabus: "Программа", lessons: "Уроки",
    add: "Добавить", edit: "Редактировать", remove: "Удалить", confirm: "Подтвердить", close: "Закрыть", search: "Поиск", filter: "Фильтр", all: "Все", none: "Нет",
    contactForm: "Связаться / Поддержка",
    recycleBin: "Корзина", emptyBin: "Очистить корзину", recycleBinEmpty: "Корзина пуста", recycleBinNote: "Элементы автоматически удаляются через 7 дней", restore: "Восстановить", deletedAt: "Удалено", permanentDelete: "Удалить навсегда",
    email: "Почта", emailAccounts: "Почтовые аккаунты", addConnection: "Подключить аккаунт", connectEmail: "Подключить почту", chooseProvider: "Выберите почтовый сервис:", emailAddress: "Адрес электронной почты", noEmailConnections: "Нет подключённых аккаунтов", connectEmailDesc: "Подключите Gmail или IMAP для автоматического анализа", lastSync: "Последняя синхронизация", neverSynced: "Не синхронизировано", sync: "Синхронизировать", confirmDisconnect: "Отключить почтовый аккаунт?", emailSummary: "Сводка по почте", recentEmails: "Недавние письма", emailInsights: "Аналитика почты", emailsAnalyzed: "писем проанализировано", oauthNote: "После сохранения вы будете перенаправлены для аутентификации.", password: "Пароль", back: "Назад", connect: "Подключить",
    editItem: "Редактировать элемент",
    nutrition: "Питание и сон", dreams: "Карта мечты", shopping: "Покупки", payments: "Доходы и расходы", notesTab: "Заметки", sharingTab: "Общий доступ",
    accessibilitySettings: "Настройки доступности", fontSize: "Размер шрифта", highContrast: "Высокий контраст", disableAnimations: "Отключить анимации", bigCursor: "Большой курсор", highlightLinks: "Выделить ссылки", reset: "Сброс", accessibilityStatement: "Заявление о доступности", skipToContent: "Перейти к основному содержанию", reduceFontSize: "Уменьшить шрифт", increaseFontSize: "Увеличить шрифт",
    creditCard: "Кредитная карта", connectCreditCard: "Подключить карту", creditCardProvider: "Поставщик карты", username: "Имя пользователя", syncNow: "Синхронизировать", importCSV: "Импорт CSV", importCreditCard: "Импорт выписки", transactions: "Транзакции", noTransactions: "Нет транзакций", lastFourDigits: "Последние 4 цифры", cardDisplayName: "Название карты", syncing: "Синхронизация...", syncSuccess: "Синхронизация завершена", syncError: "Ошибка синхронизации", disconnectCard: "Отключить карту", confirmDisconnectCard: "Отключить эту карту?",
    bankConnections: "Банковские подключения", connectBank: "Подключить банк", bankConnectStarted: "Открыто окно подключения банка", bankConnectError: "Ошибка подключения банка", bankDisconnected: "Банковское подключение удалено", noBankConnections: "Нет банковских подключений. Нажмите 'Подключить банк'.", syncComplete: "Синхронизация завершена", deleteError: "Ошибка удаления", loginRequired: "Войдите снова", emailConnected: "Почтовый аккаунт подключён", oauthError: "Ошибка открытия OAuth", bankAndCredit: "Банк и кредит",
    changePassword: "Изменить пароль", currentPassword: "Текущий пароль", newPassword: "Новый пароль", confirmPassword: "Подтвердить пароль", passwordChanged: "Пароль изменён", passwordMismatch: "Пароли не совпадают", theme: "Тема", darkMode: "Тёмный режим", lightMode: "Светлый режим", systemMode: "Системный",
    a11yCommitment: "Обязательство по доступности", a11yCommitmentText: "Мы стремимся сделать Tabro доступным для всех пользователей, включая людей с ограниченными возможностями, в соответствии с WCAG 2.1 уровня AA.", a11yWhatWeDid: "Что мы сделали", a11yLimitations: "Известные ограничения", a11yLimitationsText: "Некоторые компоненты могут быть не полностью доступны. Мы постоянно работаем над улучшением.", a11yContact: "Свяжитесь с нами", a11yContactText: "Обнаружили проблему с доступностью? Свяжитесь с нами через форму на сайте.", lastUpdated: "Последнее обновление",
    a11yFeatureKeyboard: "Полная поддержка навигации с клавиатуры", a11yFeatureRtl: "Поддержка RTL", a11yFeatureHeadings: "Правильная иерархия заголовков", a11yFeatureAria: "ARIA-метки на интерактивных элементах", a11yFeatureContrast: "Достаточный цветовой контраст", a11yFeatureSkip: "Ссылка перехода к содержимому", a11yFeatureTheme: "Тёмный и светлый режимы", a11yFeatureForms: "Формы с чёткими метками",
    incomeAndExpenses: "Доходы и расходы", totalRemaining: "Итого осталось", excellentSurplus: "Отлично! У вас профицит 👏", warningOverspend: "Внимание — расходы превышают доходы ⚠️",
    income: "Доходы", expenses: "Расходы", overdue: "Просрочено", budgetTarget: "Цель бюджета", budgetSaved: "Цель бюджета сохранена ✅",
    expensesLabel: "Расходы", targetLabel: "Цель", budgetExceeded: "Превышение на", budgetRemaining: "Осталось",
    setBudgetTarget: "Установить цель бюджета", editing: "Редактировать", saveBudget: "Сохранить", cancelBudget: "Отмена",
    weeklyPeriod: "Еженедельно", monthlyPeriod: "Ежемесячно", quarterlyPeriod: "Ежеквартально", yearlyPeriod: "Ежегодно",
    rule503020: "Правило 50/30/20", needs: "Потребности", wants: "Желания", savings: "Сбережения", targetPercent: "Цель",
    expenseBreakdown: "Распределение расходов", fixedExpenses: "Постоянные расходы", variableExpenses: "Переменные расходы",
    incomeTab: "Доходы и расходы", historyTab: "История", addTab: "Добавить", guidesTab: "Руководства", aiAdvisor: "ИИ-советник", bankCreditTab: "Банк и кредит",
    noPaymentsYet: "Нет платежей. Добавьте доход или расход для начала!", noHistoryYet: "Нет данных. Добавьте доходы и расходы для просмотра истории.",
    current: "Текущий", detail: "Подробности", allItems: "Все элементы",
    incomeType: "Доход", expenseType: "Расход", incomeName: "Название дохода (зарплата, фриланс...)", expenseName: "Название расхода (аренда, электричество...)",
    amount: "Сумма", paymentMethod: "Способ оплаты (карта, наличные...)", chooseCategory: "Выбрать категорию", recurringExpense: "Повторяющийся доход/расход (ежемесячно)",
    addIncome: "Добавить доход", addExpense: "Добавить расход", incomeAdded: "Доход добавлен ✅", expenseAdded: "Расход добавлен",
    aiFinancialAdvisor: "Финансовый ИИ-советник", askAboutMoney: "Задайте вопрос о финансах...", monthlySummaryBtn: "Месячный итог",
    monthlySummaryPrompt: "Дайте мне подробный месячный итог: что улучшить, что хорошо, и следующие шаги.",
    exportLabel: "Экспорт", descriptionCol: "Описание", amountCol: "Сумма", typeCol: "Тип", categoryCol: "Категория", paidCol: "Оплачено", dateCol: "Дата", recurringCol: "Постоянный", methodCol: "Способ оплаты", paymentsSheet: "Платежи",
    balance: "Баланс", error: "Ошибка",
    catSalary: "Зарплата", catFreelance: "Фриланс", catHousing: "Жильё", catRent: "Аренда", catMortgage: "Ипотека", catGroceries: "Продукты", catFood: "Еда", catFuel: "Топливо", catTransport: "Транспорт", catElectricity: "Электричество", catWater: "Вода", catGas: "Газ", catInternet: "Интернет", catPhone: "Телефон", catInsurance: "Страхование", catBills: "Счета", catShopping: "Покупки", catEntertainment: "Развлечения", catEducation: "Образование", catHealth: "Здоровье", catSavings: "Сбережения", catInvestments: "Инвестиции", catOther: "Другое",
    guideSaving: "Руководство по экономии", guideInvest: "Как правильно инвестировать", guideImpulse: "Избегайте импульсивных покупок", guideTips: "Финансовые советы",
    guide503020Rule: "Правило 50/30/20", guide503020Text: "Разделите доход: 50% потребности, 30% желания, 20% сбережения.",
    guidePayYourselfFirst: "Платите себе первому", guidePayYourselfFirstText: "При получении зарплаты автоматически переводите 10-20% на сберегательный счёт.",
    guide24HourRule: "Правило 24 часов", guide24HourRuleText: "Перед покупкой дороже $50 подождите 24 часа.",
    guide52WeekChallenge: "Челлендж 52 недели", guide52WeekChallengeText: "Неделя 1 = отложите $5, неделя 2 = $10... К концу года у вас будут тысячи.",
    guideEmergencyFund: "Сначала резервный фонд", guideEmergencyFundText: "Перед инвестированием создайте резервный фонд на 3-6 месяцев расходов.",
    guideCompoundInterest: "Сложный процент", guideCompoundInterestText: "$500/месяц при 8% доходности = $450,000 через 20 лет.",
    guideETF: "Индексные фонды (ETF)", guideETFText: "90% инвесторов не обыгрывают индекс. Инвестируйте в фонды, отслеживающие S&P 500.",
    guideIdentifyTriggers: "Определите триггеры", guideIdentifyTriggersText: "Скука, грусть, FOMO. Спросите себя 'что я сейчас чувствую?'",
    guideWorkHours: "Считайте в рабочих часах", guideWorkHoursText: "Товар за $100, зарплата $20/час = 5 часов работы. Стоит ли?",
    guideDeleteApps: "Удалите приложения для покупок", guideDeleteAppsText: "Дополнительное усилие открыть браузер = меньше импульсивных покупок.",
    guideAutomation: "Финансовая автоматизация", guideAutomationText: "Настройте автоматические переводы в день зарплаты.",
    guideAvalanche: "Метод лавины", guideAvalancheText: "Сначала погасите долг с самой высокой процентной ставкой.",
    guideDisclaimer: "⚠️ Примечание", guideDisclaimerText: "Вся информация здесь носит исключительно образовательный характер и не является профессиональной инвестиционной рекомендацией.",
    january: "Январь", february: "Февраль", march: "Март", april: "Апрель", may: "Май", june: "Июнь", july: "Июль", august: "Август", september: "Сентябрь", october: "Октябрь", november: "Ноябрь", december: "Декабрь",
    personalDetails: "Личные данные", personalDetailsDesc: "Ваше имя будет отображаться в общих листах.", firstName: "Имя", lastName: "Фамилия",
    designAndColors: "Дизайн и цвета", designDesc: "Выберите цветовую схему и светлый/тёмный режим.", colorScheme: "Цветовая схема", displayMode: "Режим отображения", light: "Светлый", dark: "Тёмный",
    font: "Шрифт", fontDesc: "Выберите подходящий шрифт.",
    interfaceLayout: "Макет интерфейса", layoutDesc: "Выберите удобный стиль навигации.",
    layoutTabs: "Вкладки", layoutTabsDesc: "Верхняя панель", layoutSidebar: "Боковая панель", layoutSidebarDesc: "Сворачиваемое меню", layoutCompact: "Компактный", layoutCompactDesc: "Выпадающие меню", layoutBottomNav: "Нижняя навигация", layoutBottomNavDesc: "Мобильная навигация", layoutHamburger: "Гамбургер", layoutHamburgerDesc: "Выпадающее меню", layoutCards: "Карточки", layoutCardsDesc: "Главная панель", layoutSplitView: "Разделённый вид", layoutSplitViewDesc: "Навигация + контент",
    customColorsTitle: "Пользовательские цвета", customColorsDesc: "Измените цвета текущего дизайна.", primaryColor: "Основной цвет", backgroundColor: "Цвет фона", cardColor: "Цвет карточки", resetToDefault: "Сбросить",
    pinActivated: "Код доступа активирован", pinDeactivated: "Код доступа отключён", pinUpdated: "Код доступа обновлён!", settingsError: "Ошибка обновления",
    changePasswordTitle: "Смена пароля", passwordMinLength: "Пароль должен быть не менее 6 символов", changing: "Изменение...",
    deleteAccount: "Удалить аккаунт", deleteAccountDesc: "Удаление аккаунта навсегда удалит все ваши данные.", deleteMyAccount: "Удалить мой аккаунт", deleteConfirmFirst: "⚠️ Все данные будут удалены навсегда.\n\nПродолжить?", deleteConfirmFinal: "Последнее подтверждение — удалить аккаунт?", deleteEmailSent: "Письмо с подтверждением отправлено.", deleteEmailSentShort: "Будет отправлено письмо с подтверждением.", deleteRequestError: "Ошибка отправки запроса",
    customListsDashboards: "Пользовательские списки и панели", customListsDesc: "Создавайте списки и панели для отслеживания чего угодно.", displayedInDashboardBadge: "На панели", nameChanged: "Название изменено",
    templateTasks: "Список задач", templateTodo: "Список дел", templateShopping: "Список покупок", templateTracking: "Список категорий", templateLearning: "Список чтения", templateKanban: "Канбан", templateCustom: "Пользовательский",
    createCategory: "Создать категорию", addListDashboard: "Добавить список/панель", enterName: "Введите название", enterStatus: "Введите хотя бы один статус", dashboardAdded: "Панель добавлена!", dashboardCreateError: "Ошибка создания", deletedSuccessfully: "Удалено", deleteError2: "Ошибка удаления", deleteConfirmBoard: "Удалить \"{name}\"? Все элементы будут удалены.",
    tabVisibility: "Видимость вкладок", tabVisibilityDesc: "Выберите, какие вкладки отображать.",
    notifications: "Уведомления",
    hebrewDate: "Еврейская дата", hebrewDateDesc: "Показывать еврейскую дату на главной панели.", showHebrewDate: "Показать еврейскую дату",
    languageTitle: "Язык", languageChoose: "Выберите язык интерфейса",
  },
} as const;

type TranslationKey = keyof typeof translations.he;

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  dir: "rtl" | "ltr";
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "he",
  setLang: () => {},
  t: (key) => translations.he[key],
  dir: "rtl",
});

const RTL_LANGS: Language[] = ["he", "ar"];

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(getStoredLanguage);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("ui-language", newLang);
    localStorage.setItem("app-language", newLang);
    // Trigger sync to DB
    window.dispatchEvent(new CustomEvent("site-appearance-change"));
  };

  useEffect(() => {
    const isRtl = RTL_LANGS.includes(lang);
    document.documentElement.dir = isRtl ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  useEffect(() => {
    const syncLanguage = () => setLangState(getStoredLanguage());

    window.addEventListener("storage", syncLanguage);
    window.addEventListener("site-appearance-change", syncLanguage);

    return () => {
      window.removeEventListener("storage", syncLanguage);
      window.removeEventListener("site-appearance-change", syncLanguage);
    };
  }, []);

  const t = (key: TranslationKey): string => {
    return translations[lang]?.[key] || translations.he[key] || key;
  };

  const dir = RTL_LANGS.includes(lang) ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
